### ISSUE TITLE
Buggy Pathing in Red Library

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#101]
Seen a suspect constantly run left and right in the room up top with 2 entrances, a door to the left and the open doorway to the right.

**Comment by jose21crisis** [comment]
Just call it "The room Sierra 1 is covering"
I've seen that before, is annoying as fuck, specially when you want to provide sniper cover to the team and he just moves left to right without him allowing you to hit him.

**Comment by eezstreet** [comment]
Try rebuilding the paths for that map in the editor and see if anything comes up.

**Comment by T-MaxWiese-T** [comment]
Fixed in V7. Could be closed

**Comment by eezstreet** [comment]
Closed in favor of #101, which has more details and information.
