### ISSUE TITLE
G36K is called G36C ingame(weapon selection menu).

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#102]
Self explanatory.

**Comment by jose21crisis** [comment]
wrong.....G36C is called G36K in code......the real weapon model is a G36C, but got called G36K in code because of reasons.

**Comment by theengineertcr** [comment]
Please close this then pls.

**Comment by jose21crisis** [comment]
G36C is shorter than the G36K. The G36K is almost as long as an M4. The G36C is as long as the MP5A4. Also, the G36K comes standard with a 3.5x scope. The G36C comes standard with iron sights
