### ISSUE TITLE
Tactical helmet

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#104]
After selecting the Tactical Helmet under the "protection" tab, the left and right arrows stop working and it becomes impossible to select any other headgear.

edit: After reading around, it sounds like the issue is that you start with the NVGs selected, but they aren't actually unlocked, so after switching to the tactical helmet they become unavailable.

**Comment by theengineertcr** [comment]
Requesting this to be closed. Tactical headgear is the only tactical equipment you have at the start of a campaign, gas mask and others will unlock as you progress.

**Comment by kevinfoley** [comment]
The bug is that you start a new game with the NVG selected, which you aren't actually allowed to use, and when you press the arrow it changes to tactical headgear and then stays on that. Since it's not obvious you're not supposed to start with NVG, I would call it a bug.

**Comment by eezstreet** [comment]
It's more of an issue with the default loadout being wrong. Not exactly a bug, but something to keep in mind with the next release. I'll mark it as Verified for now until I fix the loadouts to not include NVGs by default.

**Comment by theengineertcr** [comment]
One solution would be to do a check on when switching a campaign profile. It'll see what items are currently unlocked in the campaign, check the loadout of each officer, then set all items that are currently equipped but not unlocked to defaults. Default Primary: Carbine. Default Secondary:M1911 Default head gear:Tactical Helmet.

Alternatively, have each individual profile memorize their current officer loadouts so when you start a new profile, it'll already know that the officer loadouts will be the default weapons until changed.

**Comment by eezstreet** [comment]
The most current files do not have this bugged.
