### ISSUE TITLE
AI officers should pause before entry after throwing CS

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#105]
During an "open and CS" or "breach and CS" action, the AI officers will enter the room immediately after throwing the CS gas grenade. This doesn't give suspects enough time to succumb to the gas. AI should wait 1 - 2 seconds before entry.

**Comment by sandman332** [comment]
Yes, to many times they just go into a room and get injured or killed because the gas has not started yet.
