### ISSUE TITLE
Cannot punch AIs

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#108]
I have chased a suspect, hispanic male, in the Arcade mission. I could not punch him as he was fleeing and as he was interacting with the door even though I was in point blank range.

**Comment by eezstreet** [comment]
Need more information. What weapon was equipped? How far away were you?

**Comment by theengineertcr** [comment]
G36C, point blank.

**Comment by theengineertcr** [comment]
This does not depend on mission but the pawn itself and I will be putting new info regarding this bug as it happens to not just fleeing suspects but to civilians and suspects standing still or doing anything.

**Comment by theengineertcr** [comment]
Video showing this:https://www.youtube.com/watch?v=14mknIn0Mqc&feature=youtu.be

**Comment by eezstreet** [comment]
After adjusting the melee range again, this bug doesn't happen anymore.

**Comment by theengineertcr** [comment]
I have had this occur again in SEF V6 test version 5. Fleeing hispanic male
in atcade. This has not been fixed.
