### ISSUE TITLE
G36C uses idle animations of the M4

### ISSUE THREAD

**Issue by jose21crisis** [eezstreet/SWATEliteForce#110]
SWAT hold the G36C by a imaginary foregrip.
Might be related to this, which is on the G36C section in SWATEquipment.ini

IdleWeaponCategory=IdleWithG36
IdleWeaponCategory=IdleWithMachineGun

Both are there, which one we want?

**Comment by theengineertcr** [comment]
I believe idle with G36C might be the right one.

**Comment by theengineertcr** [comment]
There is no difference when I switched them.  They aren't holding the foregrip either, they're holding the right side of the gun. 

Image 1 FP view:http://puu.sh/vb4KC/0ab41cfdea.jpg

Image 2 TP view:http://puu.sh/vb4LO/52cd1aaf7c.jpg

**Comment by jose21crisis** [comment]
I mean AI Officers, players use them fine. Last time I played I saw Reynold hold his G36C by a foregrip.

**Comment by eezstreet** [comment]
IdleWeaponCategory is an array, it uses all of those idle animations at random. I only replicated the base game's logic, so it's either a bug with the system at large or a bug in the original game. 

Does it happen with the AKM or the Commando? Both of those use IdleWithMachineGun and don't have a foregrip.

**Comment by jose21crisis** [comment]
Will check as soon as I can

**Comment by eezstreet** [comment]
It seems to happen for the Commando as well.
