### ISSUE TITLE
Suspects can stand up after being arrested

### ISSUE THREAD

**Issue by jose21crisis** [eezstreet/SWATEliteForce#115]
![shot00003](https://cloud.githubusercontent.com/assets/25305497/24775108/8505293c-1ae9-11e7-8554-d43b4d46620c.PNG)
Look at the image........ do I need to say more?
I can also post a video where it happens on base game, not only SEF.

**Comment by eezstreet** [comment]
Nice, this doesn't seem to be only a multiplayer issue like I thought.

**Comment by theengineertcr** [comment]
Reminds me of the bug where a suspect stood up and opened a door in convenience store when we were playing multiplayer. How does this happen?

**Comment by theengineertcr** [comment]
I have found the cause of the bug. If you stun someone, then stun them again, they'll stand up. This happens on all grenade types, pepperspray, pepperball gun, Beanbag rounds, Baton rounds, Punching, but not on tasers.
