### ISSUE TITLE
CS gas delay

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#116]
The reason I added the CS gas delay wasn't for the protection of the officers, it was because it isn't realistic for the team to charge through the door the second the gas goes off as if it was a flashbang. The gas should realistically need at least a few seconds to spread around the room and start incapacitating the suspects.

I like the idea of having the team go in sooner if they are wearing gas masks, but IMHO they should still wait at least a few seconds for the gas to subdue the suspects before they go charging through the door.

**Comment by sandman332** [comment]
I agree.  I don't see a real swat team rushing into a room after gas thrown even if they have a mask on.  They need to wait a bit for it to disperse and affect people.  They could be injured or killed.
