### ISSUE TITLE
AI can't see through windows

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#118]
E.g. on side 3 of "Sisters of Mercy Hostel", you can shoot at the suspects through the glass, they'll run around confused and might even stop right on the other side of the window but can't see you.

Maybe this is an engine limitation, since it seems like every level was carefully designed to have as few transparent windows as possible. It's frustrating because there were plenty of real windows in SWAT 3 and the AI could see through them just fine...

**Comment by theengineertcr** [comment]
Same happens in A-bomb when you are on the top floor looking down at the stage.

**Comment by eezstreet** [comment]
This is really dependent on the maps themselves, for example the AI can see through the glass on doors in St. Micheal's Medical Center and they can see through the glass in the server room on Red Library Offices.
