### ISSUE TITLE
Pointing a Shotgun at a door...

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#128]
If you have a Shotgun and point it at a door knob, you'll get the breach with shotgun if you have a remington 870. I remember eez saying he removed this for C2 so you can shoot the knob without accidentally pulling out C2 but it seems the breaching shotgun icon still pops up. 

How to replicate:Equip a lethal shotgun and a remington 870. Walk to door, point at door knob. Shotgun will be lowered, breaching shotgun icon will appear.

**Comment by jose21crisis** [comment]
Well, it is preferable to use the proper breaching shotgun with proper breaching ammo than a standard shotgun with not-so-proper ammo. Still, this is something to be looked into.

**Comment by eezstreet** [comment]
This is intended behavior; if you have the breaching shotgun it will switch to the breaching shotgun instead, but if you stand a good distance away you can shoot without that context showing up.
