### ISSUE TITLE
M16A1 has wrong magazine size for some ammo types

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#131]
Specifically, it seems that JHP and JSP ammo for the M16 have 30 rounds in the magazine while they have 20 rounds for AP and FMJ.

**Comment by jose21crisis** [comment]
My mistake, should be 20 rounds for all ammo types

**Comment by theengineertcr** [comment]
Does this apply to any other weapons or just the M16A1?

**Comment by eezstreet** [comment]
Just that weapon, as far as I know.
