### ISSUE TITLE
Punching range is too long

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#134]
You can punch someone from 2-3 meters, which is an absurd distance. In first person view your punches don't even go near the person and in third person it also looks really far.

**Comment by theengineertcr** [comment]
https://www.youtube.com/watch?v=bk2LPO2-sH4&feature=youtu.be

**Comment by eezstreet** [comment]
Need a good value estimate as to what the range should be. Currently it's at 170.
