### ISSUE TITLE
SWAT AI distance for Pepperspray

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#135]
They stand way too far before starting to pepperspray, leading them to miss most if not the entire canister.  Maximum distance before starting to pepperspray should be reduced to an even closer amount.

**Comment by eezstreet** [comment]
I have a change in mind for this.

**Comment by theengineertcr** [comment]
Still not good enough, SWAT spray when they don't enter a room and miss entirely. Had it happen in Conveniance Store bathroom.

**Comment by eezstreet** [comment]
Is this still an issue after the recent sensor changes?
