### ISSUE TITLE
Funtime Amusements has people with too high of a morale

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#137]
You can pepperball someone, pepperspray them, nade them and even tase someone and they won't  comply. Had to tase someone twice after pepperballing and pepperspraying him just get him to fully comply in Funtime Amusements on _normal_ difficulty.

**Comment by eezstreet** [comment]
If there are other maps with high morale, please name them.
I looked and it seems that they might have *a little* too high of a morale, some people have up to 1.5 morale.

**Comment by jose21crisis** [comment]
TBH I think no one, not suspects, not civilians, should go above 1.0 morale points. They shouldn't even go beyond 0.95, so that they have a very small chance to comply even on the later levels

**Comment by theengineertcr** [comment]
Should be dependant on the archetypes.
