### ISSUE TITLE
Suspects aim with invisible guns(Victory Imports)

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#140]
Suspects do their gangsta shoot animation with no gun in hand(heard a gun bounce noise when his body hit the floor).

**Comment by eezstreet** [comment]
Screenshot?

**Comment by theengineertcr** [comment]
Only happened once, will do another check later.

**Comment by theengineertcr** [comment]
This is a bug with AMD graphic cards where some static meshes, blocks and etc will appear to be transparent/see through or completely invisible.
