### ISSUE TITLE
Officer Compliance Animation(s) With Less Lethal Shotguns Broken (V5)

### ISSUE THREAD

**Issue by sandman332** [eezstreet/SWATEliteForce#142]
Hello,
With the new V5 of SEF the animations officers use for ordering compliance are broken on the less lethal shotguns.  Instead, they seem to use the pistol compliance animations which look very weird.

This is believed to be because LTL shotguns are no longer considered "shotguns" and are now there own weapon category, so the animations in "OrderComplianceAction" don't set LTL shotguns compliance animations because there is no check for them.

**Comment by eezstreet** [comment]
You are correct, beanbag shotguns aren't considered Shotguns anymore, which is why the issue crops up. I am going to add a field to SwatEquipment.ini for that.
