### ISSUE TITLE
"TriggerOfficerDownSpeech" Is Using A Broken Version (SEF V5)

### ISSUE THREAD

**Issue by sandman332** [eezstreet/SWATEliteForce#143]
Hello,
The "TriggerOfficerDownSpeech" is broken and using a wrong version.  Jose came up with the idea instead of officers saying "Officer Down" they had lines for saying specific officers were down.  He then implemented it but later realized it didn't work (gathering what I read on discord) so if I remember correctly he made a fixed version, but it didn't get into V5 of SEF and the broken version is still there.
```

function TriggerOfficerDownSpeech(pawn Officer)
{
//    TriggerSpeech('ReportedOfficerDown', true);
    if (Officer.IsA('OfficerBlueOne'))
    {
        TriggerSpeech('ReportedB1Down');
    }
    else if (Officer.IsA('OfficerBlueTwo'))
    {
        TriggerSpeech('ReportedB1Down');
    }
    else if (Officer.IsA('OfficerRedOne'))
    {
        TriggerSpeech('ReportedR1Down');
    }
    else
    {
        TriggerSpeech('ReportedR2Down');
    }
}
```
This doesn't even really work, and if Officer Blue Two goes down they will say Officer Blue One is down instead.

Thanks!

**Comment by eezstreet** [comment]
Need additional testing to make sure that my commit fixed it.

**Comment by eezstreet** [comment]
So apparently this was some miscommunication; Jose added a PR that fixed it and I didn't even notice his fix was in there. However I'd still like to make sure that this is fixed via testing.

**Comment by jose21crisis** [comment]
Yeah, I'm pretty sure I fixed this.  Sandman tested it, so I think is good
