### ISSUE TITLE
Dynamic Music to play after C2 breach?

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#147]
Stinger grenades, flashbangs and suspect gun shots are loud noises that trigger Dynamic music. So why not C2 as well? Just a simple suggestion.

**Comment by eezstreet** [comment]
Sure, it could be done.

**Comment by jose21crisis** [comment]
I would say that anything that would make SWAT 3 go into dynamic mode shold trigger the dynamic music in the mod. Flashbangs, C2, gunshots from both sides.....

**Comment by theengineertcr** [comment]
Only if the gun is not silenced sure. I didn't want dynamic music to be spammed a lot but okay. I always try to extend chain dynamic music in SWAT 4 convenience store because I love it so much

**Comment by jose21crisis** [comment]
I would honestly make it last longer.......I think it only lasts 30 seconds right now. I would make it last 60-90 seconds.

**Comment by theengineertcr** [comment]
That would be too much if we add SWAT gunfire to make dynamic music. Either that, or we get a new system of dynamic + stealth like SWAT 3
