### ISSUE TITLE
Unauthorized deadly force while suspect is aiming his weapon at me...

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#148]
If you go too close to a suspect, they autoaim their weapon. I've had an instance where a suspect still counted as an unauthorized kill while he was fleeing and I got too close to the point where he turned and aimed his gun at me.

**Comment by eezstreet** [comment]
You have to shout at them first, I believe, in order for it to not be Unauthorized Use of Deadly Force.

**Comment by theengineertcr** [comment]
I have but he fled. Then I shot him as he AIMED his weapon at me.

**Comment by sandman332** [comment]
Yes that issue is fixed with the new threat changes jose did in his PR.  The flee action was still using an old version that made the enemy not be a threat when they fled.  This was before they implemented suspects attacking while fleeing.

**Comment by theengineertcr** [comment]
This is false

**Comment by kevinfoley** [comment]
I believe I am still seeing this bug as well.
