### ISSUE TITLE
Unauthorized kill on a suspect still aiming his weapon after asked for compliance

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#149]
Self Explanatory. What changes did you guys do to the new threat system? 

Video: https://www.youtube.com/watch?v=TPfeMWkO_Ps&feature=youtu.be

**Comment by kevinfoley** [comment]
I am also intermittently running into this issue.

**Comment by eezstreet** [comment]
This is actually a vanilla/TSS bug. If you lean around an object, it will consider your point of origin as the origin of the shout, so if your origin gets blocked (like it does in the video, by the freight doors) it will consider you as shouting into the wall and not shouting at the suspect.

**Comment by theengineertcr** [comment]
It has nothing to do with leaning around objects or not as earlier tests didn't revolve around me leaning. Also, he still happens to get unauthorized kill after aiming, you don't need to yell for compliance for a kill to be authorized.

**Comment by eezstreet** [comment]
Right, but the particular video you showed is what's causing it in that specific instance.

**Comment by theengineertcr** [comment]
Actually, that's false. I lean around corner and call out for compliance all the time and they comply fine. This is a completely different problem regarding the new threat system(which seems to not be as good as it used to).

**Comment by theengineertcr** [comment]
Here's a video of an instance where this happened
https://www.youtube.com/watch?v=P29-tnMY_Ss&feature=youtu.be

**Comment by kevinfoley** [comment]
I'm a little confused; is this issue any different than #148  ?

**Comment by theengineertcr** [comment]
Doesn't seem like it, you can delete issue #148 The only difference is that eez thought this was a bug regarding TSS, which it isn't at all.

**Comment by kevinfoley** [comment]
I agree that this seems to be a new bug in the last week or so (though I'm not 100% confident about that). My guess would be that it is a side effect of the changes to AI aiming behavior made by @jose21crisis but I haven't gone over his code in detail so I'm not sure.

**Comment by jose21crisis** [comment]
@kevinfoley Just checked the videos, and is probably a side effect of the aiming behavior. My best guess is that is not calling for the BecomeAThreat() function.

**Comment by eezstreet** [comment]
I'm going to split up the threat issues into a few different issues because there's several different threat-related bugs that occur.
