### ISSUE TITLE
Officer Jennings is considered a Suspect(Officer voice lines)

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#155]
Officers interact with Jennings wrongly. "Shut up!" and what not.

**Comment by jose21crisis** [comment]
They have to keep his cover, don't they?

**Comment by theengineertcr** [comment]
Then why does he call out "Officer Jennings" and why did a suspect kill him?

**Comment by eezstreet** [comment]
That's a specific case that we can work around.
