### ISSUE TITLE
Odd sniper bug?

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#160]
When Sierra 1 or 2 spot a threat, you cannot switch to the next Sierra until a couple of seconds pass as they report.

**Comment by eezstreet** [comment]
Intentional, the game wants you to look through those sniper viewports when they spot a threat.

**Comment by sandman332** [comment]
Never liked this.  Always found it annoying especially if I was already using the viewpoint and wanted to close it.

**Comment by theengineertcr** [comment]
Can we remove it at least? It really is annoying...
