### ISSUE TITLE
Shout for Compliance bugged when leaning around objects

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#164]
When leaning, the game considers your origin as the location that you are shouting for compliance from, and not from where you are looking. As a result, if you lean around an object (which doesn't change your position) and shout at something, it won't register properly as you having shouted at the target.

**Comment by theengineertcr** [comment]
Are you sure this is true eez? I have shouted while leaning AND have gotten AI to comply. Updating this with a vide to show this.

**Comment by theengineertcr** [comment]
https://www.youtube.com/watch?v=GB-yuCZntqk&feature=youtu.be

**Comment by eezstreet** [comment]
hm! It might not for the purposes of compliance then, but for the penalty system it might.
The penalty system is a bit weird in general though. I think this issue can be closed, since it was changed.
