### ISSUE TITLE
Unknown threat issues

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#165]
There is currently an issue where sometimes suspects who are aiming at you get docked as a penalty despite them clearly threatening you.

https://www.youtube.com/watch?v=P29-tnMY_Ss&feature=youtu.be
https://www.youtube.com/watch?v=x6Jc6BqoDEs&feature=youtu.be
https://www.youtube.com/watch?v=TPfeMWkO_Ps&feature=youtu.be

**Comment by theengineertcr** [comment]
This is already fixed.

**Comment by eezstreet** [comment]
Might have been refined further with Jose's latest changes. Need to do more testing to be sure.

**Comment by theengineertcr** [comment]
I'll be showing a video of it. As far as I'm concerned, if you shout, they aim, no penalty.

**Comment by eezstreet** [comment]
After a bit of testing, I can safely say that this is fixed.
