### ISSUE TITLE
Wildgunner instantly opening fire without turning

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#181]
Self explanatory, could've sworn I've seen this issue being reported in the git before...

**Comment by eezstreet** [comment]
Could you clarify what you mean? I haven't been able to reproduce anything quite like that, myself.

**Comment by theengineertcr** [comment]
Go behind wildgunner, press f, then be prepared to take on his m249

**Comment by theengineertcr** [comment]
Video showing this:https://www.youtube.com/watch?v=mEc7aQwJ1xU&feature=youtu.be
Video showing how broken WildGunner is:https://www.youtube.com/watch?v=UHgndAqgbWI&feature=youtu.be

**Comment by eezstreet** [comment]
This was was fixed in PR #212 but never closed, so I am doing this now.
