### ISSUE TITLE
SWAT spamming loss of suspect visual repeatedly

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#185]
Had an Officer take cover behind an object with a belligerent suspect and he kept spamming "he's gone". If a Suspect is behind cover, Officer will constantly spam it as well.

**Comment by theengineertcr** [comment]
Skip until you are 30 seconds in: https://www.youtube.com/watch?v=fVSsqrimVWk&feature=youtu.be

**Comment by sandman332** [comment]
Known issue this is because every time an officer takes cover or cant spot a suspect they play the line because they lost them.

**Comment by kevinfoley** [comment]
This is fairly game-breaking; the squad AI refuses to accept orders and becomes useless if they can see a distant suspect in cover.

**Comment by kevinfoley** [comment]
@jose21crisis  Since this issue was almost certainly caused by 7015b7a , would you mind taking a look at it?
