### ISSUE TITLE
"MeatBarn_Moretti" Has No Voice

### ISSUE THREAD

**Issue by sandman332** [eezstreet/SWATEliteForce#19]
Hello,
I would like to help with bug reporting for this mod, I will add updates to the Issues section if it is okay with you guys.  For now I will make each separate issue it's own issue instead of adding multiple ones together.  Please let me know if you would like it done differently, or not at all.

I see that "MeatBarn_Moretti" is set to use "SimonGowan" voice override, but because there is no context set for the voice (It is set to only trigger the lines for him on the casino level) the character has no voice.

**Comment by eezstreet** [comment]
Hi, thanks for the information. Moretti is still in the process of having VA work done.

**Comment by sandman332** [comment]
I am going to close this issue then, I just thought his voice was bugged, nice to see it is being worked on. thank-you.
