### ISSUE TITLE
Crashing in multiplayer frequently

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#191]
People seem to be crashing *very* frequently in multiplayer. No error log, just the game freezing and crashing with a generic Windows error message. Definitely something new in 5.1 as it doesn't happen in 5.0 and I've got 5+ reports about it now.

(The commit causing it is somewhere between a4d64ca1f6c64a56292e95c8947149c207ddee58 and be228a6f5fabbd388a9ada404b0ca17a97d264bd)

**Comment by eezstreet** [comment]
Possibly related to commit 844e86db058f1df4aa32f2c17a83288df48d4018 ?

**Comment by kevinfoley** [comment]
I don't have anyone to test multiplayer with, but I'll see if I can reproduce if I host a server with my desktop and connect from my laptop.

**Comment by kevinfoley** [comment]
As far as I can tell from the log output, when a player issues compliance to a suspect, if the suspect complies and decides to drop his weapon, the game gets stuck in an infinite loop until it crashes:

    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().
    ScriptLog: (t=313.839): ---SGPC::ClientAIDroppedActiveWeapon(). dropper=SP-Arcade.SwatEnemy5
    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().
    ScriptLog: (t=313.839): ---SGPC::ClientAIDroppedActiveWeapon(). dropper=SP-Arcade.SwatEnemy5
    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().
    ScriptLog: (t=313.839): ---SGPC::ClientAIDroppedActiveWeapon(). dropper=SP-Arcade.SwatEnemy5
    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().
    ScriptLog: (t=313.839): ---SGPC::ClientAIDroppedActiveWeapon(). dropper=SP-Arcade.SwatEnemy5
    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().
    ScriptLog: (t=313.839): ---SGPC::ClientAIDroppedActiveWeapon(). dropper=SP-Arcade.SwatEnemy5
    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().
    ScriptLog: (t=313.839): ---SGPC::ClientAIDroppedActiveWeapon(). dropper=SP-Arcade.SwatEnemy5
    ScriptLog: (t=313.839): SP-Arcade.SwatEnemy5$---SwatEnemy::NotifyClientsToDropAllWeapons().

(Note that due to a copy-paste mistake I made on line 785 of `SwatEnemy`, every other line contains "NotifyClientsToDropAllWeapons". This doesn't mean the wrong function is getting called, just that the function is logging the wrong name. )

The infinite loop is presumably caused by `NotifyClientsToDropActiveWeapon`:

    function NotifyClientsToDropActiveWeapon()

    {

        local Controller i;
        local Controller theLocalPlayerController;
        local SwatGamePlayerController current;

        Assert( Level.NetMode == NM_ListenServer || Level.NetMode == NM_DedicatedServer );

        mplog( self$"$---SwatEnemy::NotifyClientsToDropAllWeapons()." );

        theLocalPlayerController = Level.GetLocalPlayerController();
        for ( i = Level.ControllerList; i != None; i = i.NextController )
        {
            current = SwatGamePlayerController( i );
            if ( current != None && current != theLocalPlayerController )
            {
                current.ClientAIDroppedActiveWeapon( self );
            }
        }
    }

However, since I copied the logic from `NotifyClientsToDropAllWeapons()` and just changed which function it calls on the client, I don't understand why my code goes into an infinite loop but `NotifyClientsToDropAllWeapons()` does not go into an infinite loop. Maybe there's some simple typo I'm just not seeing. Are you able to spot any issues?

**Comment by eezstreet** [comment]
I found the problem,

`SwatGamePlayerController.ClientAIDroppedActiveWeapon` calls `SwatEnemy.DropActiveWeapon` which calls `NotifyClientsToDropActiveWeapon` which calls `SwatGamePlayerController.ClientAIDroppedActiveWeapon`. It's calling itself over and over, basically.

**Comment by kevinfoley** [comment]
I see where the loop happens but not why. If you look at the `DropAllWeapons` chain, you will see the logic is almost identical, so I don't understand why `DropActiveWeapon` causes a loop and `DropAllWeapons` doesn't.

A possible fix is to move the if/notify down a few lines so the DropActiveWeapon function won't call them if the Enemy doesn't have a weapon:

    simulated final function DropActiveWeapon(optional vector WeaponSpaceDropDirection, optional float DropImpulseMagnitude)

        {

	    local HandheldEquipment ActiveItem;

            ActiveItem = GetActiveItem();

            if (ActiveItem == None) return;

	    if ( Level.IsCoopServer )
                NotifyClientsToDropActiveWeapon();

    	    if (ActiveItem == GetPrimaryWeapon() || ActiveItem == GetBackupWeapon())
            {
		    DropWeapon(ActiveItem, WeaponSpaceDropDirection*DropImpulseMagnitude);
	    }
        }
