### ISSUE TITLE
Iron Sights status

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#198]
_Note: this information copied from the original pull request_

These commits add a basic working iron sight implementation to the game. They build on the code that @jose21crisis was working on for iron sights, but I simplified the code and added some new features.

You will move the weapon to look down its sights when you press the 'zoom' key. In addition to support for aiming down the sights, I also added a `ViewInertia` property to weapons. The `ViewInertia` property controls how responsive the weapon is when you move. A weapon with a higher inertia will sway to the sides more when you turn, and will take longer for you to align the iron sights. 

Of course SWAT 4 wasn't designed with iron sights in mind, and there are some issues. It might be better to make this a separate branch. 

## Updates
- 4-21-17: Added support for iron sight rotation offset. Set the rotation and location offsets for 1911, Glock, P226, MP5ks, and M870
- 4-24-17: Idle animations are disabled while aiming down sight. Added support for suppressed MP5, MP5SD6, and M4 Super 90. (MP5SD6 is unusable due to animation issues)
- 4-27-17: Added console commands for adjusting the iron sight parameters for the active weapon, useful for calibrating the weapons more quickly. **Finished calibrating all campaign weapons**. Added support for separate location/rotation offsets for when you aren't aiming down sight, so I could fix the damn P90.
- 5-02-17: Aim-down-sight speed partially separated from inertia so I could reduce the inertia for all weapons without speeding up the ADS animation
- 5-04-17: Fixed inertia/ADS speed being affected by framerate
- 5-30-17: Calibrated position of multiplayer weapons (AKM, M16, Uzi, etc)

## Console commands
The effects of each of these commands lasts until the current mission ends. They are intended to help with deciding upon final values to put in SwatEquipment.ini. **Note that you must have a space between the command and the values, and cannot have any spaces within the parentheses.**
- `SetIronSightOffset (x=0,y=0,z=0)` - adjust the position of the iron sights
- `SetIronSightRotation (pitch=0,yaw=0,roll=0)` - adjust the rotation of the iron sights. Note that adjusting the pitch or yaw will have a *severe* impact on the position; in other words, you'll need to adjust the offset a lot to compensate
- `SetWeaponViewOffset (x=0,y=0,z=0)` - adjust the position of the weapon when not aiming down sight
- `SetWeaponViewRotation (pitch=0,yaw=0,roll=0)` - adjust the rotation of the weapon when not aiming down sight
- `SetWeaponViewInertia 0.5` - adjust the view inertia of the weapon (how much it moves around and how fast you raise and lower the sights). The range is 0 - 1, but good values range from about 0.25 to 0.55. Use larger values for heavier weapons.

## Known Issues
- The weapon models tend to clip through the camera if you run forward while aiming down sight
- ~~The weapon idle animations make it difficult to aim. Hopefully there's an easy way to tone them down or disable them when you're aiming down the sights~~
  -  After idle animations are disabled, they are not re-enabled until you change weapons or move the crosshair over a target that causes you to lower your weapon (e.g. another officer)
- Since the view models were never intended to be used with iron sights, many of the weapons are missing faces on the right side of the weapon. Depending on the weapon and how quickly you are turning, you might be able to see holes in the right side of the gun.
- Inertia values will probably need lots of fine-tuning
- Crosshair still appears on top of sights
- The default MP5SD6 animations can't be used with iron sights, because the fingers are wrapped so far around the barrel that they block the sights 
- The HK33A2 can't be used with iron sights because it has a... flashlight? attached where a scope would be, completely obscuring the sights. Huh?
- ~~For weapons that have a different rotation when zoomed, the rotation should be tweened rather than changed instantly~~

**Comment by eezstreet** [comment]
The inertia stuff seems a bit choppy, I've been working on a way to smooth it out hopefully (and also maybe make the weapon position tilt up/down at extreme angles)

**Comment by eezstreet** [comment]
Upon further examination, it seems that the jerkiness is related to the changes made to SwatPlayer.uc to get the delta time.
Could it be done by changing it to use a delta of the previous frame's calculation's result?

**Comment by kevinfoley** [comment]
@eezstreet  The jerkiness is definitely _not_ caused by the change to get the delta time. I have spent many hours messing around with this so I'm very confident about that. It was certainly jerky before I made the change and isn't any different afterward if the system is hitting 60fps. While I know exactly what the _cause_ is, I haven't been able to fix it yet. The reason the inertia is jerky is because mouse movement is never perfectly linear. 

First off, some background which you probably already know but is worth repeating: the view model is positioned and rotated in world coordinates, so every time you move or look around, updateHandsForRendering() moves the view model in front of the camera. Even if you move the mouse while standing still, the position of the view model has to be updated. 

The way the inertia system works is by interpolating the view model towards the player's new location over several frames, rather than moving it there all at once. Currently this works by reducing the distance by a _percentage_ each frame. So for example, if the weapon's ViewInertia is 0.7, then we reduce the distance from the viewmodel's current position to its target position by `1 - 0.7 = 30%` each frame (assuming 60fps; it will move less distance per frame if the FPS is over 60 or more distance per frame if it's under 60, the end result being that it moves the same distance per second regardless of framerate)

If you hold down one of the movement keys (easiest to observe with strafing), you will see that the inertia causes the weapon to move to a fixed position and stay there. This is because movement speed is constant. Let's say that when strafing you move 10 units per frame. After the first frame, the weapon will move by 3 units (30% of 10). After the second frame, the weapon is 17 units behind the player, so it will move by 5.1 units. The distance that the weapon moves per frame increases by a smaller amount each frame until it is moving the same distance as the player each frame; in this example, after about 10 frames the weapon will be about 23 units behind the player each frame.

However, when we move the mouse, the motion isn't linear each frame. You might move the mouse enough to turn 3 degrees one frame, 5 degrees the next frame, 1 degree the next frame, 3 degrees the next, etc. This means that the distance our character is moving each frame isn't linear, and because of this the inertia causes the weapon to move by a different amount every frame, causing it to appear twitchy.

The easiest way to demonstrate this is by intentionally twitching the mouse in very small increments. Let's say you twitch it two degrees to the right, then pause for an instant, then twitch it another two degrees, and so on. Each instant that you're not moving the mouse, the weapon continues to move towards the center of the screen. Then you twitch it again and the distance increases, causing the view model to visibly reverse direction for an instant. You stop twitching again and the weapon reverses direction towards the center of the screen again.

I haven't tested this yet, but presumably the weapon inertia will be less jerky if you have mouse smoothing enabled. If so, maybe that will give us an idea of how to solve the problem without actually having to force users to enable smoothing.

**Comment by eezstreet** [comment]
Hi, let me clarify what I meant, because I don't think I conveyed it well.


Removing the changes you made to UpdateHandsForRendering (so that it uses more or less the same behavior) results in some strange behavior when moving around. I'm somewhat confident that this is due to the function being called from SwatPlayer.Tick() instead of where it was originally because the position hasn't been updated at that point in the function.


As far as a solution to your problem goes, we could perhaps store the result of previous frames calculations and use a four-point spline interpolation (maybe) to generate the best results.

________________________________

**Comment by kevinfoley** [comment]
Ah, okay, I understand what you're saying now. That would definitely be a separate issue from what I was describing. I haven't noticed any new jerkiness since I made the change, but I haven't tried it with the old code.

I think originally `UpdateHandsForRendering()` was only called from one place, but jose changed it to be called from numerous different functions (for reasons that weren't clear to me) in commit 16f928893bca84b39542241be899e73bff984ab9 . If there's another way to get the deltaTime, maybe we can go back to calling `UpdateHandsForRendering()` from its original source

**Comment by eezstreet** [comment]
I tried experimenting a bit with moving the config options from Hands into a new class called HandsConfig and adding some information from previous frames, but I got a bit stuck with the iron sights stuff, so I figured it might be wiser to let you take care of it.
________________________________

**Comment by eezstreet** [comment]
Any luck in getting the jerkiness smoothened out?

**Comment by kevinfoley** [comment]
I haven't had a chance to look at it more; I'll try to get to that tonight.

**Comment by eezstreet** [comment]
So I see you've added some spline points - do we know if there's a spline class somewhere that can handle it, or do we need to write our own?

**Comment by kevinfoley** [comment]
This is my first time working with Unreal, so I'm still learning my way around. All I've been able to find that might be relevant is this, but I'm not sure if it's exactly what we need or even if it's supported in the version of Unreal that SWAT 4 uses: https://wiki.beyondunreal.com/Legacy:Spline

**Comment by kevinfoley** [comment]
@eezstreet  Are we allowed to edit the original weapon models for this, or does that fall outside the scope of "mod"? I don't see a clear answer in the EULA.

**Comment by eezstreet** [comment]
Editing the original weapon models would be fair-game.
________________________________

**Comment by kevinfoley** [comment]
Cool. It looks like I can import the meshes into Blender and edit them, but the import script totally botches the armatures. If I edit the meshes, could @theengineertcr or someone with 3DS Max recombine them with the proper armatures?

I'm sort of decent with Blender but by no means a pro, so my inclination would generally be to just mirror the left side of the gun to save time. This would mean the model wouldn't be 100% accurate for most of the guns (e.g. no ejection port), but since the right side of the gun is only barely visible when you're using iron sights, I don't think that would be a huge deal. What do you think, Nick?

**Comment by eezstreet** [comment]
I'll leave this up to @theengineertcr to figure out what he wants to do here. I think he wanted to make the right side of the gun for himself but I'm not sure.

**Comment by kevinfoley** [comment]
I figured out a way to fix the armatures (in a hex editor...). Here's an example of the MP5 with right side added.
![mp5 with right side](https://cloud.githubusercontent.com/assets/7231744/26815073/faeb63f8-4a3e-11e7-98de-7cd7b9b7ed17.jpg)

**Comment by theengineertcr** [comment]
Nice job! I don't think any of my work can out-class his.I'm focusing more on learning 3ds max so I can aid in animations and props. Kevin seems much more skilled though, so I'll leave it to him.
