### ISSUE TITLE
SWAT AI never hits the the lock when using the breaching shotgun

### ISSUE THREAD

**Issue by jose21crisis** [eezstreet/SWATEliteForce#210]
We screwed something up. The team can't hit the lock at all. They never do. The second shot hack always has to kick in. Anything we cahnged about the aiming system still remains in the code?

**Comment by eezstreet** [comment]
I don't think they were ever accurate to begin with, and that's why they put that in.

**Comment by jose21crisis** [comment]
They definitely weren't 100% accurate in the base game. But right now they don't hit the lock at all.

**Comment by kevinfoley** [comment]
Just change it so the lock automatically breaks instantly after the first shot. There's no reason we should be making it this completed.

**Comment by kevinfoley** [comment]
Should this one be closed now?
