### ISSUE TITLE
New commands need to be supported by speech command interface

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#214]
- RESTRAIN ALL
- SECURE ALL
- DISABLE ALL
- SEARCH AND SECURE

See 6c28fb6

**Comment by eezstreet** [comment]
The SHOTGUN & CLEAR, C2 & CLEAR etc commands that were added in v5 are also not supported yet.

**Comment by kevinfoley** [comment]
Where are these commands? The only one I see in the regular command interface is "search and secure"

**Comment by eezstreet** [comment]
Those commands appear in place of RESTRAIN, DISABLE and SECURE EVIDENCE on the command menu (those commands are contextual only)

________________________________

**Comment by eezstreet** [comment]
These are supported by SRI as of d85a6e2d56217d06a87854a2d421199848d90c03
