### ISSUE TITLE
Remodel or remove HK33A2?

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#217]
I don't think any sane person is ever going to rail mount a Maglite to the _top_ of their assault rifle in a way that completely obscures the iron sights. This weapon looks absurdly silly and really has no place amongst the other weapons. If we can't remove the flashlight from the top of the gun, I say remove the gun from the game.

![hk33a2](https://cloud.githubusercontent.com/assets/7231744/26032188/f2969fc4-3841-11e7-92cd-d6d53c9f4627.png)

This is not to be confused with the HK33A2 marksman rifle that has a scope mounted on top of it. That variant is fine.

![scoped hk33a2](https://cloud.githubusercontent.com/assets/7231744/26032200/506d320c-3842-11e7-9d63-4de6673bd2bb.png)

**Comment by theengineertcr** [comment]
On it.

**Comment by theengineertcr** [comment]
Just to be clear, do you want the flashlight entirely removed, or to have it be out of the way of the ironsight location(maybe moved to the right side of the gun?)

**Comment by jose21crisis** [comment]
We can just kill it with fire ... or make the flashlight be on the foregrip (not the Maglite, make it like the MP5 foregrip)

**Comment by theengineertcr** [comment]
Well...you didn't answer my question but here it is: http://puu.sh/vQSdY/a6d012519e.jpg

**Comment by theengineertcr** [comment]
Here's the second version(MP5 foregrip) http://puu.sh/vQSx0/accb97581a.jpg

**Comment by kevinfoley** [comment]
Looks good to me.

**Comment by theengineertcr** [comment]
Guess we can get this closed?

**Comment by eezstreet** [comment]
Implemented.
