### ISSUE TITLE
"All Missions" career bugs

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#218]
I've added a few missions from the Mega Map Pack and am trying them out in the All Missions career. The All Missions career is very buggy:

- [x] Your scores for custom maps are not saved
- [x] After failing a custom map, pressing "restart mission" starts a random mission from the SEF campaign instead of the last custom mission you played
- [x] After ending a mission and returning to the 'select mission' menu, the SWAT officer in the menu background is shown in the T pose for several seconds until the menu loads
- [x] The missions don't always appear in alphabetical order

**Comment by eezstreet** [comment]
I think these should be split into separate issues for each one, that way they can be ticked off as they're done.

**Comment by kevinfoley** [comment]
I changed the bullet points to checkboxes; does that work?

**Comment by eezstreet** [comment]
Yep, didn't know that was a thing. Nice.
