### ISSUE TITLE
AI going rogue

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#221]
If any member of the squad can see any suspect, all members of the squad will report that they are "busy" and refuse all orders. They may try to chase down the suspect, encounter additional enemies, and get stuck in a loop that effectively causes them to go completely rogue and continue sweeping the level until they are killed or all suspects are arrested/downed/killed.

This is a **serious bug** that can **_severely and permanently derail_** missions by causing the player to completely lose control of his team. Large missions with broad lines of sight are most heavily affected. Possibly related to AI changes over the last month, as I don't recall this being a serious issue before mid-April.

The custom map "Newfort" from the Mega Map Pack is a particularly good mission to test this on. The AI will go rogue immediately and will sweep the entire level until they are all killed.

This one is completely ruining the game for me. I hope we can figure out a fix soon.

**Comment by sandman332** [comment]
Can confirm this.  Such a big bug.  I wish you could have a command to call them Even if they are busy, they drop what they are doing and come back to you.

**Comment by sandman332** [comment]
Makes me not even want to play the game

**Comment by kevinfoley** [comment]
Maybe this could be fixed by not considering the squad as busy unless a suspect is actually shooting at them?

**Comment by sandman332** [comment]
That and not aiming at them or a hostage, etc.  There definitely are some tweaks that could be made to them.

**Comment by sandman332** [comment]
I have located where all the busy stuff is controlled.

"OfficerTeamInfo.uc"
Source/Game/SwatAICommon/Squads/OfficerTeamInfo.uc

The main function that seems to control it is this.

```
private function bool AreOfficersBusyEngaging()
{
	local int i;
	local Pawn Officer, Assignment;

	// make sure we update our current assignments
	SwatAIRepo.GetHive().UpdateOfficerAssignments();

	// go through the officers, if one of them has an assignment, then we can't follow the command
	for(i=0; i<pawns.length; ++i)
	{
		Officer = pawns[i];

		Assignment = ISwatOfficer(Officer).GetOfficerCommanderAction().GetCurrentAssignment();

		if (Assignment != None)
			return true;
	}

	// didn't find an officer with an assignment
	return false;
}
```

There is also other spots where it calls this.  I'm going to test and see if totally removing their busy stuff and see how they perform.  I'm expecting they will drop what they are doing and do as I say, but I am not sure what the side effects will be.

**Comment by sandman332** [comment]
I feel like this issue began or at least became way more noticeable when this was introduced.
https://github.com/eezstreet/SWATEliteForce/commit/7015b7a51ee45aabca13d7ffaffb79ed6d6a692e
The whole "OfficerLostPawn" just seems like more of an issue then needed, might be why the devs never added it in.

**Comment by kevinfoley** [comment]
Recently the AI tends to stand around doing nothing more than running off to complete the mission by themselves. Here's a shot with Tyrion values of them standing around doing nothing because they can see some unrestrained hostages in the far distance.
![busyai](https://user-images.githubusercontent.com/7231744/27165311-0741af62-5148-11e7-8ed9-886728b10be9.png)

**Comment by eezstreet** [comment]
This doesn't seem to be a problem anymore after recent changes.
