### ISSUE TITLE
AI doesn't verbally respond to "cover" command

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#232]
For every other command you get a "roger", "affirmative", etc, but not for "Cover"

**Comment by sandman332** [comment]
I beileve there are a couple commands that also dont give a response to you.  Can't remember though.

**Comment by eezstreet** [comment]
Conversely, it would appear that the AI responds *twice* to some commands, like Pick Lock and Mirror Under the Door (?)

**Comment by sandman332** [comment]
They also don't say anything when you issue the "close door" command.  And yes the commands you mentioned above plus the "check for traps" command they respond 2 times.
