### ISSUE TITLE
Admin Mod

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#235]
Seeing as how we have access to the client, which is more than what most admin mods such as Gez, MarkMod etc do, we have an interesting opportunity to add some admin mod features.
Everything here should be considered *ideas* that are worth discussion. Ideally they would be aimed at public servers who need to self-moderate.

**ALL** of these features are optional and do not apply in a campaign CO-OP game.

 - [ ] Flag system - players can pick a flag for their country which is visible on the chatbox and/or the MP panel
 - ~~Prohibited flags - server admins can disallow players from certain countries~~
 - [x] Ban by IP - server admins can ban people by their IP address
 - [ ] Ban by name - server admins can ban specific people by their name (or ban specific usernames, such as "Player" or "Operator")
 - [ ] "Friendly" ban - Players will be allowed to join, but will be kicked after 30s, notifying them that they are banned
 - [x] Message of the day - The server has up to 5 Messages of the Day which will play in rotation, on a duration customizeable by the host.
 - [ ] Vote kickspec - players can vote to kickspec people
 - [ ] Auto RoE enforcement - the server can automatically kick, kickspec, ban, etc people who break the RoE (customizeable by the server host)
 - [ ] Leaderboard system - the game will keep track of the previous score (and leaders) and the best score (and those leaders). The game will inform players about these when the map starts. When a new high score is done, the chat is notified about it.
 - [ ] Individual score - The server can keep a separate, individual score for a player. The best leader on a map is noted when the map starts.
 - [ ] Ranks - A player may "rank up" on a server either by score, time played, admin designation (to mark donors, good players, rambos, etc), or a combination of these. The ranks are customizeable by the server host.
 - [ ] Colored names - Names can be colored by team or by rank
 - [ ] Leaders can Global Chat only - Add option to only allow leaders to use global chat (by forcing messages to go to team chat) - doesn't apply if not ingame
 - [ ] Privileged ranks - Ranks may gain new privileges, like kicking people (good for an Admin rank)
 - [ ] Penalty/Objective disabling - A server may choose to have its objectives or penalties disabled entirely. For fun.
 - [ ] Remove specific penalties - A server may choose to disable certain penalties from taking effect, like tasing teammates. 
 - [ ] Disable weapons, ammo, tactical equipment, etc via blacklist or whitelist
 - [ ] Replicated disabled equipment - Equipment that is disabled on the server will be replicated to the client, and that equipment won't be a selectable option.
 - [ ] Word filter - Whitelist/blacklist for chat, with options to either block the chat, warn the player, etc
 - [ ] Disable spectator chat - Option to disable spectator chat (except when all players are dead)
 - [x] Chat spam prevention - Option to only allow X messages per Y seconds
 - [ ] Command spam prevention - Option to only allow X commands per Y seconds
 - [ ] Allcaps prevention - Option to remove messages that are in allcaps, force them to lowercase, or to warn for using uppercase letters
 - [ ] Ping monitoring - Option to kick players automatically who are above X ping for Y seconds

**Comment by theengineertcr** [comment]
I am against flag bans/country bans.

**Comment by sandman332** [comment]
Flag bans make sense.  Want someone with a Nazi flag going around?

**Comment by theengineertcr** [comment]
Cant wait for american servers banning people for living in europe even
though they get a ping under ping limit...

**Comment by eezstreet** [comment]
The flag ban can be removed, the only real purpose I can see for it is for servers I've seen that are Brazilian-only (for instance) or to ban the default flag.

**Comment by theengineertcr** [comment]
Just please no flag prohibitation. And the "default" flag is what? It's not affecting anyone...you don't need to kick people for having default flag, ban some names sure but prohibiting flags or people from playing because they live in a certain country shouldn't be a thing.

**Comment by eezstreet** [comment]
The default flag would be white. 
We can eliminate country bans, it's not a big deal and I don't see it being used often.

**Comment by eezstreet** [comment]
This admin system spec no longer matches what the system will look like. I'm closing this issue.
