### ISSUE TITLE
LaunchSEF.exe does not support Windows XP

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#247]

**Comment by jose21crisis** [comment]
The comment said that "LaunchSEF.exe is not a Win32 application" .... you wrote it for x86 or x64? Or they work for both?

**Comment by eezstreet** [comment]
It's not a 64 bit/32 bit issue. It's that the app needs to be compiled with XP support. It's really simple to do, I just need to recompile it.

________________________________
