### ISSUE TITLE
M1 Super 90

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#249]
The core SWAT 4 files include a first-person model for an M1 Super 90 shotgun that currently isn't used in the game. Worth adding? 
![m1 super 90](https://user-images.githubusercontent.com/7231744/26866974-5261fc44-4b18-11e7-80e3-226f9dfadcd3.png)

**Comment by theengineertcr** [comment]
I'd say yes since the first person anims are similar to the m4.

**Comment by jose21crisis** [comment]
Aside from making it a suspect-only weapon, which benefits it would have over the M4 Super 90 if ti becomes a player-usable weapon?

**Comment by kevinfoley** [comment]
It doesn't necessarily need to have any benefits over the M4 Super 90. It could have slightly weaker stats and unlock earlier in the campaign. It's probably redundant when the game already has three other shotguns, but I'm always in favor of variety.

**Comment by eezstreet** [comment]
I certainly think it would be worth adding, just for the sake of variety. It should be noted that it doesn't have a flashlight and that it uses a different caliber (20 gauge vs 12 gauge of the other shotguns) which would make it a lighter choice.

**Comment by jose21crisis** [comment]
The First Person model does have a flashlight. And as far as I've seen, the Benelli M series shotguns are available both in 12 Gauge and 20 Gauge. However I think Law Enforcement only use the M1 in its 12 gauge variant. They did that in SWAT 3 at least.

**Comment by eezstreet** [comment]
Implemented.
