### ISSUE TITLE
Suspects with the broken SWAT mesh

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#251]
This is more of a question than a bug, I think. I have a "bleeding-edge" branch on my local copy where I pull all of the changes from all of the branches. A while back, somebody (jose21crisis, I think?) added support for the heavy armor mesh on suspects, but they would appear with messed-up textures (e.g. white body, bright red armor, "SWAT" written on the back). This went away and then at some point when moving files around I accidentally brought it back. What file do I need to edit so I don't get the heavy armor mesh with broken textures? Is that EnemyArchtypes.ini?

**Comment by jose21crisis** [comment]
Ok, I edited the next files
SwatAICharacter.uc
SwatAICharacterConfig.uc
CharacterArchetype.uc
AI.ini
EnemyArchetypes.ini

Check those and make sure that there are lines for both Heavy and No Armor meshes

**Comment by kevinfoley** [comment]
What should I change to tell it not to use the heavy armor mesh that currently renders bright red?

**Comment by kevinfoley** [comment]
@jose21crisis  What should I change to tell it not to use the heavy armor mesh that currently renders bright red?

**Comment by jose21crisis** [comment]
Don't remember exactly which one.

**Comment by eezstreet** [comment]
This has been corrected for a while now.
