### ISSUE TITLE
Redesign Quick Mission Maker from scratch

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#253]
Quick Mission Maker was always kind of janky in my opinion. Here's what I propose to replace it.

*Quick Mission Maker Overhaul*
From the Quick Mission Maker menu, you have two main areas: Archetype Creator and Quick Mission Builder. COOP-QMM is totally different now and instead of being able to create QMMs together, the map list fills with quick missions that you can add to a rotation.

**Archetype Creator**
From here, you can create custom archetypes which you can use in your maps. This is broken up into different sections:

*Basic Archetype Info*
You can create a Civilian, Suspect, Collectable and Trap archetype and give it a name.

*Appearance*
For civilians and suspects, you can choose mesh, texture and basic equipment, as well as voice type.
For inanimates, you can choose mesh.
Common meshes and textures will appear in a dropdown box, but you can choose to manually enter a texture and/or mesh path.
These can all be randomized.

*Function*
For civilians, you can pick their morale here.
For suspects, you can pick which gun(s) they use, their morale and what their skill level is. This part can be randomized.
For traps, you can pick whether they are an alarm or bomb trap.
This area is greyed out for collectables.

**Quick Mission Builder**
Players will no longer be able to collaborate on QMMs in CO-OP QMM like they could before. This wasn't really a good idea and it prohibited being able to run a dedicated server.

*Map and Objectives*
You can pick which map and what objectives you want. This is roughly the same as the original QMM however there are some new objectives:
 * Rescue most of the civilians: Must save at least 50% of the civilians
 * Disarm all of the bombs: Disarm any bombs present on the map

When Disarm All of the Bombs is marked, the Bomb Count in Objects gets increased to 1/1.
Unlike the original QMM, there is a checkbox: `Use custom maps`. Ticking it will disable the briefing on the map (like All Missions) and allow you to use custom maps.

You can also pick where you want snipers to set up. You can pick how many snipers you want present (up to 2) and a list of locations where you want them to set up.

*Squad*
You can choose Lone Wolf, or disable some AI-controlled officers. (This doesn't apply in CO-OP QMM). You can pick which entry position you would like. You can pick to either force a custom loadout, or restrict specific equipment items.

*Civilians*
You can specify which archetypes (from the Archetype Builder) you would like. After adding a civilian archetype to the list, you can specify whether to override their morale from the base.
You can also specify some archetypes that you would like to spawn as incapacitated.

*Suspects*
Similar to the Civilians tab, just with suspects. You can override specific suspect archetype's weapons and morale if you would like.

*Objects*
Here you can pick traps and collectable archetypes you would like to spawn. There is also a bomb count here (you need to enable the Disarm All Bombs objective to enable this). You can pick however many traps and collectables you want.

**Key changes**

 * Archetype builder
 * Spawn traps
 * Spawn collectable objects
 * Spawn incapacitated civilians
 * CO-OP QMM dedicated servers
 * Override only specific archetypes

**Comment by jose21crisis** [comment]
Sounds like a nice idea .... how we pull it off?

**Comment by theengineertcr** [comment]
It will be pulled off in v7

**Comment by sandman332** [comment]
I thought eez said in discord majority of the redoing would be v7, but some of the smaller stuff for it he was working on for v6?

**Comment by eezstreet** [comment]
I thought about starting with that, but I'd rather just redo all of it from scratch first.

**Comment by T-MaxWiese-T** [comment]
Could be closed
