### ISSUE TITLE
AI can't use pepper spray

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#255]
@eezstreet  Since 06717b6 , the AI can't use pepper spray correctly. They run into the target and push them around, but don't fire the spray. After several seconds of this, they may spray over the target's head without hitting the target, then put the spray away.

**Comment by sandman332** [comment]
I can confirm this started with that commit, but it also affects ALL ordered commands.  Pepper spray, taser, grenade launcher (baton), pepperball gun, less lethal shotguns, etc.  They go right up to them and push the target around, and if they can't shoot them for whatever reason within the 7.5 seconds for attacking, they timeout and forget it.

**Comment by eezstreet** [comment]
This isn't really an issue, as of latest v6.
