### ISSUE TITLE
Desert Eagle animations are terrible

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#256]
1. It starts out with the slide back instead of forward
2. The slide does not animate when you fire
3. The muzzle flash comes out of your hand instead of the muzzle
4. The shells come out of your hand instead of the slide

Unless someone can fix all these issues or we find a completely new replacement model, I propose we just remove it from the game. It seems like IG wasn't trying when they made the TSS models.

**Comment by theengineertcr** [comment]
Eez fixed the slide issue iirc and I do remember the slide moving on shots. I can fix the animations if needed.

**Comment by kevinfoley** [comment]
Unless there's another version in the Stack I haven't noticed, it does not have a firing animation and the slide doesn't move when you fire. The slide only moves when it's out of ammo.

**Comment by theengineertcr** [comment]
First 2 issues are fixed.

**Comment by eezstreet** [comment]
I have to upload it onto the Stack but 1&2 are fixed and I think 3&4 can be explained by the insane recoil on the gun. Try setting the recoil to 0 and see if that still happens.

**Comment by theengineertcr** [comment]
Can we get an update on this? What's the status on the deagle?

**Comment by eezstreet** [comment]
This is not an issue anymore, since the weapon uses a completely different model now.
