### ISSUE TITLE
Less-lethal shotgun sometimes doesn't create projectile

### ISSUE THREAD

**Issue by kevinfoley** [eezstreet/SWATEliteForce#258]
This is a rare bug. Sometimes when firing a less-lethal shotgun, no beanbag comes out. This can be observed by shooting at a person (they do not react) or at a wall (where you can see that the beanbag does not appear). The issue seems to go away after firing and reloading a few times.

Tested with 5.3 release version.

**Comment by sandman332** [comment]
Can confirm this.  I once started a mission with Jackson and Girard having both Less Lethal Shotguns (one with the normal one and one with the M870 one) and every time they shot nothing came out.  No effect came out, no actual beanbag came out either.  Had to restart the mission.

**Comment by eezstreet** [comment]
The beanbag *will* disappear if the shot occurred too far away/the shot lost all of its momentum.

**Comment by kevinfoley** [comment]
@eezstreet  I'm talking about shooting things that are 3 feet in front of you.

**Comment by eezstreet** [comment]
I've tweaked the drag a bit in the v6 branch. Let me know if this issue is still occurring.

**Comment by MattyDienhoff** [comment]
I regularly had this issue in v5.3, having upgraded to 6test3 I haven't had any more problems with disappearing beanbags since. I'll keep an eye out but this issue seems to be resolved.

**Comment by eezstreet** [comment]
Going to mark this as fixed because it's not occurring anymore according to testers.
