### ISSUE TITLE
Suspects don't drop their weapons when they are empty

### ISSUE THREAD

**Issue by jose21crisis** [eezstreet/SWATEliteForce#264]
Exactly what it says on the title. Suspects can run out of ammo and when they do, they don't drop their weapons, which can result in situations like ....
![shot00000](https://user-images.githubusercontent.com/25305497/27692931-f1d3b232-5cb5-11e7-875d-15348774c283.JPG)
... that. That suspect is armed, but apparently ran out of ammo. But he still has his gun in his hand.

**Comment by sandman332** [comment]
Not sure what the issue is, as sometimes they will drop them, and sometimes they will not.  Maybe run `debugtyrion` and see what actions are being called to figure out.

**Comment by eezstreet** [comment]
Check and see how weapon dropping is handled and see if that requires a resource to be freed first. It might be that their weapon resource is being used by the cower action (just a guess)
