### ISSUE TITLE
Door check range is very...long

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#267]
Self explanatory. Video will be provided soon.

Edit: https://www.youtube.com/watch?v=Jtfi7RRY-d8&feature=youtu.be

**Comment by eezstreet** [comment]
It's reduced as of the latest V6.

**Comment by theengineertcr** [comment]
There's still a little bit of an issue with punching where if you aim at the head of a suspect and attempt to punch them as they are right next to a closed door, it'll check the door. However, if you aim at their body, you punch them. I still think door check range is too long, can we reduce it further more? Half of what it is currently would be perfect.

**Comment by smug** [comment]
The "door checking instead of punching" still happens quite frequently as of version 6.4

**Comment by eezstreet** [comment]
This is not an issue anymore, since in v7 the door checking was changed into optional separate keys and the issue was resolved completely otherwise (because it was checking the door swinging instead of the door model)
