### ISSUE TITLE
AI pathfinding, officers go through uncleared rooms

### ISSUE THREAD

**Issue by ggaston095** [eezstreet/SWATEliteForce#269]
There's an annoying bug:

Suppose there is a room with two doors on opposing sides, you have red stacked in one, blue in the other. You are with blue, then you order red to fall in, red opens the door and gets into the room hoping to get to your position, instead of backtracking through the safe hallway.

How possible is it to fix?

**Comment by sandman332** [comment]
Not sure how possible it is to fix.  I feel like the pathing would need to be changed for every map that has this issue, which could be more work then it's worth.

**Comment by eezstreet** [comment]
Yep. This is more of an issue of specific maps and how they're designed. Off the top of my head, FunTime Amusements is one that suffers from this. It's not really fixable unfortunately.
