### ISSUE TITLE
Make the AI be threats after they are shouted at.

### ISSUE THREAD

**Issue by jose21crisis** [eezstreet/SWATEliteForce#272]
Make this apply to all armed threats. Realistically speaking, if a suspect refuses to comply, and starts running away, you don't know what he/she could do. The suspect could go and execute a hostage (already done with Insane suspects), detonate a bomb or something else. Like this TV Tropes section puts it: 

> Hollywood Law: If an armed suspect runs from you, shooting him is considered improper use of force. While the United States does have severe restrictions on a police officer's authorization to shoot fleeing criminal suspects, this would be permissible in virtually every situation your team faces in the game. Most of the levels involve hostage situations, and an armed felon fleeing from police contact would present an imminent threat to any hostages in the area. Even in the ones that don't, a fleeing armed felon still presents an imminent risk to your team and would generally be considered a justified shoot.

Edit: Yes, I know TV Tropes is not the best place to look at info, but the point still stands

**Comment by sandman332** [comment]
Should to back to how it was done in the CommanderAction have any swat enemy be a threat like it used to be.  Instead of it only applying to insane suspects like it is now.

**Comment by eezstreet** [comment]
I don't like this idea very much. Simply making a target a threat after being shouted at allows you to spam the shout button and shoot at people willy nilly.

**Comment by sandman332** [comment]
I mean it should go back to the old way of if a enemy is ignoring compliance then he becomes a threat.  Like how it was before.  Pretty sure thats what jose meant as well.  Not if you shout at an enemy he becomes a threat.  Just if he is ignoring compliance orders.

**Comment by jose21crisis** [comment]
At least make them a threat if they start fleeing since you don't know what they might do, even if they are non-Insane.

**Comment by kevinfoley** [comment]
That's not how police procedure works. Police don't get to shoot someone just because that person is running away. It's not realistic, and it would make the game too easy.

**Comment by jose21crisis** [comment]
This one has been called of so I'll close it and move on.

**Comment by jose21crisis** [comment]
This one has been called off, so I'll just close it and move on.
