### ISSUE TITLE
Officer Ai Can NOT Deploy Pepper Spray

### ISSUE THREAD

**Issue by sandman332** [eezstreet/SWATEliteForce#273]
Hello,
The Officer Ai after the target sensor changes can no longer deploy the pepper spray on a enemy or a hostage.  They will pull out the pepper spray, and either move the target across the room aiming pepper spray at them, or they will just stand in front of the target aiming the spray eventually canceling out.

Not sure exactly what the issue is, just know it started after the target sensor changes/rewrite.

Thanks!

**Comment by eezstreet** [comment]
Corrected on latest v6.
