### ISSUE TITLE
AI auto-lightstick usage often causes them to block doorways

### ISSUE THREAD

**Issue by MattyDienhoff** [eezstreet/SWATEliteForce#276]
As in the title, when an AI officer autonomously drops a lightstick after clearing a room, they generally go back to the point of entry to do it, and then stay there until they receive a new order. More often than not this causes them to block the door, which is a minor (but frequent) annoyance.

**Comment by kevinfoley** [comment]
Don't they just move out of the way if you try to walk through the door?

**Comment by MattyDienhoff** [comment]
Unfortunately no, they're often quite stubborn about it. I've often had to spend several seconds trying to push past them, or even order them to "Move to" to get them out of the way.

**Comment by eezstreet** [comment]
This is not an issue anymore, since lightsticks are dropped at the point of clearing, not at the doorway.
