### ISSUE TITLE
Gas mask no longer obscures vision

### ISSUE THREAD

**Issue by MattyDienhoff** [eezstreet/SWATEliteForce#285]
It did in 5.3, but the overlay is gone again in 6test3. This is despite the description still saying that it restricts vision, so I'm guessing it's a bug rather than an intentional change.

**Comment by eezstreet** [comment]
As it turns out, the texture got accidentally deleted in SWAT1stPersonTex.utx. However, since this set of textures is not modified anymore, this problems resolves itself in the next beta release.
