### ISSUE TITLE
Search and Secure has random priorities.

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#288]
Officers will choose according to actor index, not based on which equipment is closer to them. Therefore, the officers will very often choose to secure equipment that is across the map first before they bother with stuff that's closer.

**Comment by sandman332** [comment]
Can confirm.  Can't it just be changed so that they select whatever is closest to them first?  Then keep moving down the line.

**Comment by eezstreet** [comment]
This is fixed in a recent commit.
