### ISSUE TITLE
Optiwand range does not match the model

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#299]
You can peak through a corner without sticking the optiwand past the wall, very confusing as people would not know when they are able to see past it and often get too close to the point where a suspect spots them. Reduce optiwand range would make it less useful, so how about I stretch out the size of the stick the cameras attached to? We can then tune the camera range to how far the camera is.

**Comment by eezstreet** [comment]
It actually does match the model. It uses the bone of the pivoting head to determine where to place the camera. If it looks wrong, it's due to the FOV of the optiwand camera.
