### ISSUE TITLE
Wrong spawn point in Wolcott Projects (QMM)

### ISSUE THREAD

**Issue by samfisher2007** [eezstreet/SWATEliteForce#310]
There is a spawn point in the mission that is located on the top of the scaffolding in the courtyard. A suspect will appear on the top and can't be restrained and also he can't run or escape from the team.

**Comment by sandman332** [comment]
Can confirm, the multiplayer version of the map has a piece added that you can access the scaffolding.  Maybe they forgot the single player version didn't have that piece or they forgot to add it to the single player version of the map.  Either way, a simple delete of that spawn point or adding the piece so they can get back over would work.

**Comment by eezstreet** [comment]
This has been corrected as of the latest test version.
