### ISSUE TITLE
[Request] Compliance Shouting

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#346]
Since Use and Shout commands are bound to one key there is an issue with shouting when it is not needed. For example when you pick evidence or close door, etc. Would it be possible to make it so the player shout voiceover is being played only when there is a non surrendered hostage/suspect in sight? The command itself could still be issued at all times (just in case), but without voiceover.

There is a similar thing in game. Player shout's "Drop your weapons!" only when there is an armed suspect in sight.

Thank you

**Comment by eezstreet** [comment]
This might be possible. I can try it at some point and gather feedback on it.

**Comment by eezstreet** [comment]
Shout and Use are now bindable to separate keys, so this might not be necessary to do anymore.
