### ISSUE TITLE
[Request] Game difficulty and AI

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#348]
It seems SEF mod uses Stechkovs AI as base, which is a lot weaker than the original SWAT4. AI improvements have made pawns to be more like a team, but suspects AI has stayed same. Also, I have noticed that bullet spread has been reduced allowing the run&gun tactic. All that makes the current version of game too easy compared to original SWAT4. Maybe it would be better to improve enemy's reaction, accuracy and damage output?

If enemy's AI could be improved, it would be nice to consider it's optimisation toward the swat pawns. Those are still underpowered compared to real player. Maybe there could be implemented a function, into the suspects AI, which would check if current target is a pawn or a player. If current target is a pawn suspect's attributes(accuracy, reaction, etc.) are being reduced and if the current target is a Player - increased.

Thank you

**Comment by eezstreet** [comment]
This isn't really a feature suggestion or a bug. So I will have to close it.
In general the game will be *much* more difficult in v7.
