### ISSUE TITLE
[Request] Merge Check Lock and Check for Traps

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#352]
I propose to merge Check Lock and Check for Traps commands into one Check Door command to improve gameplay.

Thank you

**Comment by smug** [comment]
I think it's fine the way it is right now.
Consider that very few maps have traps which means this change would potentially introduce overhead on most maps that people play. Autochecking for traps would also render them useless as their purpose is to surprise and punish the lazy player.

**Comment by eezstreet** [comment]
The CHECK FOR TRAPS command has been changed into MIRROR FOR TRAPS, and there is a combination MIRROR FOR ALL command which mirrors for contacts as well as traps. So merging the check lock and check trap commands don't make sense anymore.
