### ISSUE TITLE
FOV Auto-Calculation

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#354]
I think the player should not have a direct access to feature like FOV. I suggest to add function which would auto-calculate the most appropriate fov based on the current resolution width value. The function might check if current screen resolution is wide, if it is than check it's width value and after add a calculated modifier to a default fov value. If screen is not wide, the function is not being initialized and fov stay's default.

Also, it might be good to make main menu camera to always use default fov value only.

**Comment by eezstreet** [comment]
Disagree. Having control over the FOV is important. I hate it personally when games lock the FOV.

**Comment by sandman332** [comment]
Disagree as well.  Even to this day, people get upset when a PC game doesn't have an FOV slider and I can completely understand why.
