### ISSUE TITLE
Entry point selection

### ISSUE THREAD

**Issue by smug** [eezstreet/SWATEliteForce#366]
For singleplayer campaign mode (all missions) would it be possible to show the name of the selected entrypoint instead of just primary/secondary?
Also the tooltip for entrypoint selection is currently bugged. It says "Turn off all briefing audio." for both radio button choices even though the correct text exists in the source files (Select the secondary entry point for this mission.).

**Comment by eezstreet** [comment]
The first one is not able to be changed, because on custom maps they don't have that information available.

The second one is indeed a bug so I will flag this as that.
