### ISSUE TITLE
[BUG] AI Breaching a door with a shotgun

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#369]
SWAT officers are not acting properly if you order them to breach a door with a breaching shotgun. If they stand "properly"(First from the door has the shotgun and the second throws grenade) it is fine, but if they start to switch it gets messed up. When they start to switch one officer is being pushed to the door and keeps standing there blocking the grenade throw for other officer and placing himself in danger. It seems AI doesn't know what to do at this situation. I think he should move back and stand last in chain.

It happens when you order to all 4 officers. If order is issued to 2 man squad it is fine.

**Comment by semodo** [comment]
No, it happens with 2 man squad as well when they switch.

**Comment by eezstreet** [comment]
This needs to be examined and made sure that it's fixed.

**Comment by semodo** [comment]
There is a different bug now. If you order "Shotgun, Gas and Clear", officers will destroy the door and open it, but they won't throw the grenade nor enter the room. After they destroy the door, they are simply standing.
