### ISSUE TITLE
Incapacitation with the less lethal is always a penalty

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#37]
Incapacitating an enemy with the less lethal shotgun always results in a penalty because the target is considered stunned when they are incapacitated.

**Comment by jose21crisis** [comment]
This is probably related to the UnbecomeAThreat() function I made

**Comment by eezstreet** [comment]
Fixed via 6aeecf67e28ab4bafe217a5efc77dff2d28dc3fc
