### ISSUE TITLE
Search and Secure AI behavior

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#370]
I think when you issue Search and Secure order AI should perform it only at the room where order has been given, not on the entire map.
If you give "Open and Clear" command, for example, officers are cleaning only specific room, so I think AI knows that rooms have borders.
Thank you

**Comment by eezstreet** [comment]
It doesn't get applied on the whole map. It's a range, configurable through Command.ini (warning, breaks multiplayer compatibility)

________________________________________
