### ISSUE TITLE
Unable to switch sniper view while Sierra is reporting

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#372]
Player is unable to switch sniper view cameras while one of the snipers reports that they have spotted someone. Player can only view from the sniper which is reporting.

**Comment by eezstreet** [comment]
This is intentional behavior. There is a cooldown before you can switch to another sniper. It is designed such that when you open the sniper viewport, it will open to the one who spotted the person.

________________________________

**Comment by semodo** [comment]
Yes, I know, but since it interferes with player controls I suggested to change it.

**Comment by eezstreet** [comment]
Fixed.
