### ISSUE TITLE
[Proposal] AI behavior while wedging door

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#374]
SWAT officers should ignore door opening attempts from the opposite side of door while wedging.

If, after the "Wedge Door" order has been issued, the door has been opened, SWAT officers should continue their task anyway. They close the door by themselves and wedge it.

Thank you

**Comment by semodo** [comment]
Update: Would be nice to be able to issue wedge order to an opened door as well.

**Comment by eezstreet** [comment]
Implemented the first suggestion. I'm not sure that being able to wedge doors open is very strategically useful, but I'm open to the idea.
