### ISSUE TITLE
Wedging an opened door

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#379]
> Implemented the first suggestion. I'm not sure that being able to wedge doors open is very strategically useful, but I'm open to the idea.

I think I didn't say it clear enough. You probably think that I proposed to wedge a door in an opened state, but it is not what I meant.
The "wedge door" order option is available only on closed doors, it is absent for an opened doors. So if you  need to wedge a door which is opened you have 3 options:
- approach the door yourself, close it yourself and wedge it yourself. (The quickest way)
- approach the door and close it yourself and order to wedge it to a team.
- order a team to close the door, wait until they will approach and close it, order them to wedge it after. (The slowest way)

What I meant is to make the "wedge door" order available for the doors in an opened state. After using this command, SWAT officers would approach the door, close and wedge it. All this with one command.

**Comment by eezstreet** [comment]
Implemented.
