### ISSUE TITLE
[BUG] SCAR rifle is bugged

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#389]
- Viewing though the iron sights is impossible since the view is misaligned.
- Weapon is clipping with camera.
- Suppressed SCAR rifle uses sound of non-suppressed rifle.
- Can't use scoped version as the scope isn't transparent.

**Comment by eezstreet** [comment]
Fixed most of this. The clipping is unfortunately a problem of the FOV.
