### ISSUE TITLE
[BUG] M4 Carabine bugged

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#391]
- Full Auto fire rate is very slow, like 1-2 shots per second.
- Viewing though the iron sights is impossible since the view is misaligned.
- Disabling Iron Sights Zoom in the menu, results in a camera clipping while using iron sights.
- Fake shadows drown on rifle better be removed as they don't correspond with game's lighting and look odd.
- Can't use both silenced versions(with and without scope) as they are not rendered properly. When you spawn, first person hands and weapon are placed improperly, too far from camera and too high. Also, the original, lowpoly model is being used for the first person and third person views. If you switch weapon to another and after back to silenced M4 - it will become invisible, but it would shoot still.
- First person weapon model doesn't have the right side modeled.

**Comment by eezstreet** [comment]
Fixed all of this.
