### ISSUE TITLE
[BUG] Missing "x3" gear prefix in the loadout screen

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#392]
The 3x versions of gear have lost their 3x prefix in the menu. (Flashbang x3, Gas x3, etc.)

**Comment by eezstreet** [comment]
Where, specifically? In the long name (shown on the right side of the screen) or the short name (shown on the tactical selector)? In v7 I added a short name and long name for equipment.

**Comment by semodo** [comment]
In the Equipment menu, Tactical tab. Wedges and C2 are called properly still, but Gas, Flashbang and Sting grenades are not. You can only figure those are 3x packs from their description. They are named simply as "Gas" or "Flashbang" as the standard single versions.
