### ISSUE TITLE
[BUG] Player receives his own gear

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#393]
Player receives his own gear(optiwand for example) while checking door's lock.

**Comment by eezstreet** [comment]
I don't understand. Can you explain this better?

**Comment by semodo** [comment]
There is a new ability in v7, to give items to other officers. This feature is being triggered while the player checks door's lock, so the player gives and receives the item to himself.
You might have to press the "Fist/Door Check/Give" key on a door quickly several times to see it. It is usually easy to reproduce the bug.

**Comment by eezstreet** [comment]
I can't replicate this issue, but I can probably prevent it from happening. Does it occur when you hold the button down or what?

**Comment by semodo** [comment]
Hm, I checked it today again and it seems not to be related to the door. If you switch to any tactical item like grenade or optiwand and press the "Fist/Door Check/Give" key while being anywhere, player will give it to himself.

**Comment by T-MaxWiese-T** [comment]
Can be closed
