### ISSUE TITLE
[BUG] Door quick order option

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#395]
As I understood from the changelog, Open & Clear should be a default order only on those doors which have been checked by the player or swat officers and are not locked. Check Lock order should have still been the default order for the unknown doors.
Currently Open & Clear is a default command on all unlocked doors, even on those player didn't check.

**Comment by semodo** [comment]
Hm, it seems to work in a different way than I explained. I couldn't determine its principle still.

**Comment by theengineertcr** [comment]
I'm assuming this has to do with eez's new door roster system to make doors
randomly open/closed/locked/unlocked
