### ISSUE TITLE
[BUG] Orders are sent through the objects

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#399]
Orders are being sent through the objects. You may send orders through tables, movable office walls, boxes and other furniture. Also the transparent grid-like catwalks affected as well. 

Stechkovs Warehouse is a good map to test it since there many objects of this sort. You may use the "Move To" order command to see this bug well. You can't order team to move to a box or to a catwalk since they will be pointed thought these objects and go far after them. Also you cant order team to throw a grenade at the grid-like wall near the back entrance to the warehouse. (where the sneaky suspect used to always camp)

Also, if you will aim in the direction of the door and there would be a box, between you and door, your quick order will change to door specific and you will be able to issue it. As if the box is transparent.

This bug disallows useful tactics, please fix.

**Comment by eezstreet** [comment]
Does this happen in v6.4 *and* v7? Or just in v7?

**Comment by semodo** [comment]
v7 only.
