### ISSUE TITLE
[Proposal] Zoom-less Iron Sights Mode

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#405]
If you aim through the iron sights, you bring your weapon closer to eye, to make a precise shot. While in zoom-less iron sights mode it is opposite, player held's weapon on a considerable distance from camera, which looks quite odd. I'd say the weapon should be held same as in a zoomed mode, except without zoom. Also it would fix some of the clipping issues.

As for pistols, they are good as they are now.

**Comment by eezstreet** [comment]
The weapon is held exactly the same as in Zoomed ADS as it is in non-zoomed ADS. The only difference is the FOV.
