### ISSUE TITLE
[REQUEST] Add LVL III+ or LVL IV plates

### ISSUE THREAD

**Issue by dretax** [eezstreet/SWATEliteForce#408]
Currently SWAT 4 has "light" kevlar and "heavy kevlar".
Honestly the light kevlar equals with the heavy kevlar.
Stating the American Armor rates:

LVL II (Currently in the game)
LVL IIIA
LVL III (Currently in the game)
LVL III+
LVL IV

Now honestly LVL III is usually Ceramic plates or Steel plates, but I don't think It's that much heavy.
LVL II is capable to stop all pistol threats, and shotgun buckshots, IIIA does the same, but It's a bit more durable kevlar.
Maybe you could take this into consideration to add another light kevlar LVLIIIA or maybe change LVLIII to LVLIII+, have more weight and protection, mark it as heavy armor, and add LVLIIIA as a "medium" armor?

**Comment by dretax** [comment]
Alright. If you want to go realisticly keep in mind:

https://www.youtube.com/watch?v=dYVT9R4GX2k

https://www.youtube.com/watch?v=ZdgQ0OSZqOo

https://www.youtube.com/watch?v=duxeXrz6Pvg&t=108s

https://www.youtube.com/watch?v=d2TBoP9Aoow

If you are keeping the "Level III+, which is unlocked later in the game and is the heaviest vest, stops every round except .223 AP", I suggest adding 7.62x39 AP, and bigger rounds.

**Comment by T-MaxWiese-T** [comment]
Could be closed
