### ISSUE TITLE
[BUG] Player can't place C2 on door with alarm

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#410]
Player himself can't place C2 on door with alarm. At least from an opposite side, I couldn't test if player can place it from the same side, on top of the alarm. Officer npc placing it normally it seems.

**Comment by semodo** [comment]
Player can place it on the same side where alarm is placed, only opposite side is bugged.

**Comment by LeRutY** [comment]
That got fixed or why is this issue closed?

**Comment by semodo** [comment]
It is possible to place c2 on door with alarm, except it is less comfortable.

**Comment by LeRutY** [comment]
Yeah, I had this case on public and it worked.
