### ISSUE TITLE
[BUG] SWAT officers are not stepping away if hit by door

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#411]
In v7 officers supposed to ignore being hit by door while wedging door. They ignore it always tho. When they stand in a door way and you need to close the door, for example, you could simply hit them with door and they would step away quickly. As for now, you have to push them manually.

**Comment by eezstreet** [comment]
This is not so much a bug, as it is behavior that isn't programmed.
I can make them only ignore suspects/civilians trying to open the door, if you think that would solve the issue.

**Comment by semodo** [comment]
> This is not so much a bug, as it is behavior that isn't programmed.

Why? They step away quickly if hit by door in vanilla and previous SEF versions.

**Comment by eezstreet** [comment]
Implemented.
