### ISSUE TITLE
Options for the Settings menu

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#413]
There are several options available in game, which are drastically improving quality. Those are not available from the in-game menu, some other players might not know about those options. You may find these variables in swat4x.ini:

**For Video Menu:**

[Engine.RenderConfig]
//Those are True or False
DisableBspBumpDynamicSpecular=false - should enable more bumpmapping if false
UseRealtimeMirrors=True
// Those may vary between Low/Normal/High/UltraHigh
FluidSurfaceDetail=UltraHigh
DynamicShadowDetail=UltraHigh
GlowEffectDetail=UltraHigh
BumpmapDetail=UltraHigh
WorldDetail=UltraHigh
TextureDetail=UltraHigh

[WinDrv.WindowsClient]
// Those may vary between Low/Normal/High
TextureDetailInterface=High
TextureDetailTerrain=High
TextureDetailWeaponSkin=High
TextureDetailPlayerSkin=High 
TextureDetailWorld=High
TextureDetailRenderMap=High
TextureDetailLightmap=High

[D3DDrv.D3DRenderDevice]
UseTripleBuffering=True - improves performance
LevelOfAnisotropy=16 - may be 2/5/16 I think
TesselationFactor=1.0 - may be increased I think
TerrainLOD=100 - this might affect terrain quality.
UseXBoxFSAA=False - not sure what is this, probably Anti-aliasing?

Some of those also increase rendering distance.

No need to make separate button for each variable of course. The Texture quality buttons's drop down menu could affect all the texture related vars equally, for example.

**Sound Menu:**

[ALAudio.ALAudioSubsystem]
UseEAX=False - you could make a button for this in the sound menu,to enable EAX.
There is also an issue with 3d sound in swat4. There is a fix for it:
https://pcgamingwiki.com/wiki/SWAT_4#Audio_settings

Thank you

**Comment by eezstreet** [comment]
Some of these are dubious.

UseXBoxFSAA=true does not make any difference, and neither does changing DisableBspBumpDynamicSpecular. 

EAX only works if you apply the 3D sound fix.
