### ISSUE TITLE
21:9 resolutions are missing

### ISSUE THREAD

**Issue by martinsstuff** [eezstreet/SWATEliteForce#416]
21:9 monitors are getting more and more popular, it would be great if the resolutions could be added to the list. Except a weird aspect ratio issue with the handcuff crosshair texture, 21:9 is supported without any obvious issues in SWAT 4 (manual config edit required).

The most common ones currently are:

2560x1080, 3440x1440, and recently 3840 x 1600. There may be some more I am missing, please reply if you know any more used 21:9 resolutions!

I am not sure where is the best place to put a pull request for this so I'm posting it as an issue.

**Comment by eezstreet** [comment]
Added.
