### ISSUE TITLE
Visual Inconsistency:Chemlights

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#418]
Chemlight that are attached on all SWAT AI(and possibly online players) are green in color. However, the chemlights they drop are in their teams respective colors. I'd prefer them to be reverted to green for singleplayer as I haven't heard of special teams doing this. Of course in multiplayer it would be reasonable as it isn't really focused on realism.

**Comment by eezstreet** [comment]
Fixed.
