### ISSUE TITLE
The Suggester: [V.Berlioz's REQUEST] "...Give seasoned criminals good chances of Steel body armor."

### ISSUE THREAD

**Issue by TheSuggester** [eezstreet/SWATEliteForce#421]
(Note: I know I "technically" addressed this in **_Discord_** earlier but I'm putting it here just so people don't forget, aka "documentation" purposes.)

![capture2](https://user-images.githubusercontent.com/38480961/39088973-54356e94-458a-11e8-9ed4-785b40e37338.JPG)

"1. Buff the overall protection of Level III Ceramic to where steel is. Nerf steel to where current Level III is and give it serious vulnerability to AP. 2. Introduce "Heavy Ceramic" (NIJ Level IV) above current steel and ceramic. 3. Give seasoned criminals good chances of Steel body armor. 4. Maybe give them Heavy Ceramic from time to time."

**Comment by eezstreet** [comment]
Added in v7.
