### ISSUE TITLE
Missing text on 1600x900 resolution

### ISSUE THREAD

**Issue by nate-ryan1** [eezstreet/SWATEliteForce#425]
There appears to be a minor issue with the 1600x900 resolution that causes some text to disappear.
![1600_900](https://user-images.githubusercontent.com/39504460/40334919-75fb53c8-5d26-11e8-8cbf-cc0690af28e7.png)
As you can see, at 1600x900 resolution, the inlaid text for the tabs disappear. This effect can be replicated consistently. All of the other resolutions seem to display the proper text, such as at 1440x900:
![1440_900](https://user-images.githubusercontent.com/39504460/40334985-e77de15a-5d26-11e8-8d6b-a2df2513a88a.png)

**Comment by TheSuggester** [comment]
It seems that this is a current problem for certain resolutions as explained by eezstreet here: https://ibb.co/kfOP6T

_**IN HIS OWN WORDS**_

> it's because the resolution resizes some of the GUI elements ever so slightly, and as a result, the text vanishes because it can no longer fit the bounds that it's assigned to

> so in order to fix it, you have to edit the GUI with the GUI editor in that resolution and make the text areas bigger until it appears properly

> i've already fixed it for most of the common resolution ratios but some of the wide-widescreen ones are untouched because i wasn't able to get my resolution in that ratio

**Comment by eezstreet** [comment]
Fixed.
