### ISSUE TITLE
P226 has no shading/shadows in the LOW (Render Detail) settings.

### ISSUE THREAD

**Issue by TheSuggester** [eezstreet/SWATEliteForce#426]
(Note: This is also a visual comparison of the P226 in both LOW and VERY HIGH (render detail) settings.) 

**LOW** (Render Detail) - First 2 photos

![](https://cdn.discordapp.com/attachments/284401480125906944/452571230134992896/Swat4X_2018-06-02_16-32-15-908.jpg)

![](https://cdn.discordapp.com/attachments/284401480125906944/452571240868085760/Swat4X_2018-06-02_16-32-18-202.jpg)

**VERY HIGH** (Render Detail) - Last photos in the bottom

![](https://cdn.discordapp.com/attachments/284401480125906944/452571315451330560/Swat4X_2018-06-02_16-32-02-438.jpg)

![](https://cdn.discordapp.com/attachments/284401480125906944/452571324943171585/Swat4X_2018-06-02_16-32-05-372.jpg)

**Comment by T-MaxWiese-T** [comment]
I've tested it and can confirm it.

**Comment by beppegoodoldrebel** [comment]
remove specular texture from p226 shader to fix the issue

**Comment by wsevren** [comment]
Removed the specular texture for the p226 fixed the issue. https://drive.google.com/file/d/1MPZveAEJs_4ygKno3yYMakE4LMI2QuXk/view?usp=sharing

@eezstreet

**Comment by eezstreet** [comment]
Fixed in most recent changes to assets.
