### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by gpr17** [eezstreet/SWATEliteForce#440]
On a clean installation of SEF 6.4 over  of swat 4 gold(GOG), I have put the folder SEF as explained on tutorial
The errors that appear are:
![imagen](https://user-images.githubusercontent.com/43187911/45388479-5c133380-b619-11e8-837b-c55c07d6a30c.png)
![imagen](https://user-images.githubusercontent.com/43187911/45388485-659c9b80-b619-11e8-989d-c946a81dfdd1.png)
![imagen](https://user-images.githubusercontent.com/43187911/45388504-75b47b00-b619-11e8-9960-8feb618d7c4d.png)
![imagen](https://user-images.githubusercontent.com/43187911/45388512-7cdb8900-b619-11e8-9517-180880dff07d.png)
And then a critical error window with:

No Label

Crash Time: 09/11/18 23:22:04

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 2815 MHz with 2047MB RAM
Video: Intel(R) HD Graphics 630 (4749)

UserName: ---
ComputerName: ---
Application location: D:\Games\SWAT 4\ContentExpansion\System\

SWAT Build Number: 6.4

Procedures Transient.Procedures0 (Function SwatGame.Procedures.Construct_Void:00F3) Assertion failed, line 26

History: FFrame::Serialize <- UObject::CallFunction [SCRIPT='SwatGame.Procedures.Construct_Void' OBJ='Procedures0'] <- UObject::ProcessEvent [Function SwatGame.SwatRepo.PostBeginPlay() on SwatRepo Transient.SwatRepo0] <- BeginPlay <- UGameEngine::LoadMap <- UGameEngine::Init <- InitEngine

Next steps?

**Comment by gpr17** [comment]
5.3 is working fine, though

**Comment by thelittlefireman** [comment]
Same issue with, same error messages after upgrade 6.4 to 7.alpha

**Comment by thelittlefireman** [comment]
find the anwser : just lanch the CompileSource.bat

**Comment by Shtuffs** [comment]
I had this same issue before. Turns out that the one on github here is the source code. It won't work if you download the one from here. You can find the proper download in the discord server: 

https://discord.gg/A4SECVt
