### ISSUE TITLE
[BUG] Game close himself

### ISSUE THREAD

**Issue by Xerox96** [eezstreet/SWATEliteForce#441]
- [I have a problem, the game crashes every so often while I play, it's like it minimize the window a few seconds and then go back to the game. This repeates a couple times and then suddenly it minimizes and does not return, I can't do anything and I have to restart my computer, when is minimized I can see the different icons of the Windows taskbar (Wifi, volume, etc) but like... Weird and all around the screen. Has anyone had a problem like that? I don't know what to do.
(Sorry for my bad english)]

**Comment by eezstreet** [comment]
This sounds like an issue on your end, please see the Discord server for support.
