### ISSUE TITLE
Viewmodel FOV setting isn't saved after game reboot

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#444]
Viewmodel FOV setting slider(in the video settings submenu) isn't saved after reboot.

**Comment by eezstreet** [comment]
Need to clarify if this is related to resolution saving issues or not.

**Comment by T-MaxWiese-T** [comment]
Tested and can be closed

**Comment by smug** [comment]
> Tested and can be closed

What the hell is that supposed to mean? The issue still persists with the latest version.
