### ISSUE TITLE
Server Setup invisible

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#45]
From admin@induktio.net:

2. On my game the "server setup" was missing from the menus even while
logged in as an admin.

Running Markmod 13.1

**Comment by induktio** [comment]
Confirmed this bug occurs also when the server is installed on a plain TSS version, no server side admin mods used. The server setup menu was still missing whether logged in or not.

**Comment by eezstreet** [comment]
Possibly fixed in v5 test version

**Comment by eezstreet** [comment]
Is this issue still present?

**Comment by eezstreet** [comment]
Going to close, as it doesn't seem to be present anymore.
