### ISSUE TITLE
Ironsights remove recoil on ALL weapons

### ISSUE THREAD

**Issue by Shtuffs** [eezstreet/SWATEliteForce#456]
I know that I posted an issue about the FAL having recoil removed when ironsighting, but after trying different weapons, I found that ironsighting on any weapon removes recoil on all weapons. I don't know if you already fixed this or not, but I'm just notifying you that it isn't only the FAL that is having the problem.

**Comment by eezstreet** [comment]
Fixed in the next beta version.
