### ISSUE TITLE
Children of Taronne Tenement not working on Multiplayer

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#46]
From admin@induktio.net:

3. When we voted for SP-Tenement the server kicked all clients out
because of an unmatched count of ini files. It was the only map where
this occurred though. Required a restart to fix.

Additional information: Running Markmod 13.1

**Comment by theengineertcr** [comment]
This should be closed, recently tested and the mission works perfectly fine except for the mission completing on one objective being completed.
