### ISSUE TITLE
Wrong headgear in headcam view

### ISSUE THREAD

**Issue by jevgienij123** [eezstreet/SWATEliteForce#460]
For example I wear a regular Helmet but using my friend's headcam I see a gasmask on myself. This was a well-known 6.4 bug but seems not to be fixed in 7.0 as of yet.

**Comment by eezstreet** [comment]
Unsure how to reproduce effectively.

**Comment by jevgienij123** [comment]
What can I say, it always happens, not just sometimes so just create a 2 player game and you'll see.

**Comment by eezstreet** [comment]
Fixed.
