### ISSUE TITLE
M4 Super 90 Shells

### ISSUE THREAD

**Issue by Ghost1138** [eezstreet/SWATEliteForce#463]
M4 shotgun's shells lack of the cover the last shell has. I've temporary solved this by replacing the gun's modded .ukx animation file with it's TSS counterpart (I made a backup of the modded ukx). Of course, that messed with the iron sight position.

TSS:
![received_2428008010766701](https://user-images.githubusercontent.com/47161084/57494004-cdd17900-729d-11e9-8543-1dbf0cbf79ab.png)

SEF:
![received_391962628318853](https://user-images.githubusercontent.com/47161084/57494005-ce6a0f80-729d-11e9-9d87-aacd2847d829.png)

**Comment by eezstreet** [comment]
It [appears fine on the latest build](https://i.imgur.com/JclXzqh.png), something might be screwed up on your end.

**Comment by Ghost1138** [comment]
Well, I don't have any other mods installed excluding SEF, nor personal modifications. Besides the gun looks perfectly fine in the vanilla game.

I've the v7 beta 2 version of the mod, installed over the v6. Also, I've reinstalled multiple times, both the game and the mod, in different computers and the issue is still there 🤔
