### ISSUE TITLE
Silenced M4A1 Readying Animation

### ISSUE THREAD

**Issue by ItsToofy** [eezstreet/SWATEliteForce#467]
Using the Supressed M4A1 has a weird lack of animation, bringing up another gun shows the gun being raised, the Supressed M4A1 does not have this and just "snaps" into view.

Also, when I handcuff a suspect/hostage, the Supressed M4A1 shows up almost like its in the middle of the screen before showing back up in its proper spot.

This does not happen with the regular M4A1

**Comment by theengineertcr** [comment]
This is overreported and has already been fixed.
