### ISSUE TITLE
New M4A1 ironsights aren't lined up correctly

### ISSUE THREAD

**Issue by Shtuffs** [eezstreet/SWATEliteForce#482]
The ironsights for the M4A1 aren't lined up with the actual crosshair.

**Comment by ImmortalFishy** [comment]
Credit to JalapenoPepsi on the discord for the proper values:

Go to: SEF/System/Swatequipment.ini Search for: "M4A1" and copy in these values

;; Viewmodel and Zoom
FirstPersonModelClass=class'SwatEquipmentModels2.M4A1_FirstPerson'
ThirdPersonModelClass=class'SwatEquipmentModels2.M4A1_ThirdPerson'
IronSightLocationOffset=(X=2,Y=-6.86,Z=2.52)
IronSightRotationOffset=(Pitch=20,Yaw=0,Roll=0)

**Comment by eezstreet** [comment]
Fixed.
