### ISSUE TITLE
Scar H scoped needs adjusting

### ISSUE THREAD

**Issue by Ozoneraxi** [eezstreet/SWATEliteForce#486]
The red dot isnt aligned with the ironsight, which is confusing. Bullets will land on the red dot.
I suggest moving the ironsight just a tiny bit to the right.
\
![unknown](https://user-images.githubusercontent.com/21977238/66317126-9e449c80-e921-11e9-9a31-b0ee650c1176.png)

**Comment by Shtuffs** [comment]
I'd also like to add that both the scoped and ironsights versions of the SCAR H also have the issue where the sights just start moving to the left if you look up.

**Comment by eezstreet** [comment]
Fixed via 0f4c4f0
