### ISSUE TITLE
MP5SD aim bug

### ISSUE THREAD

**Issue by CBWardog355** [eezstreet/SWATEliteForce#487]
When I aim at a civilan or team mate, the gun lowers (as it should), but then it never comes back up until I switch to the pistol or any other tool and then back to the smg. It only happens with the MP5SD.

**Comment by eezstreet** [comment]
Please clarify which weapon: is it the Supressed MP5A2, Suppressed MP5K, Suppressed MP5K PDW, or the MP5SSD6?

**Comment by Shtuffs** [comment]
> 
> 
> Please clarify which weapon: is it the Supressed MP5A2, Suppressed MP5K, Suppressed MP5K PDW, or the MP5SSD6?

This only happens with the MP5SD6

**Comment by JohnnyThreeDee** [comment]
Can confirm this happens in v7 release build.

[Video evidence](https://youtu.be/8sGYzWoTWf8)

**Comment by T-MaxWiese-T** [comment]
"MP5SD6 wouldn't come back up after low-readying." Can be closed
