### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#495]
I also have the problem that my graphics settings, VSync and screen size are always reset when I close SWAT4 but otherwise all settings are retained.

**Comment by eezstreet** [comment]
Ensure that you have write permissions to the SEF folder.

**Comment by T-MaxWiese-T** [comment]
It would be nice if the SEF mod could fix this bug somehow. I believe that many have this problem. But if you start the SEF Lauchner as administrator it works.
