### ISSUE TITLE
XDM third-person model positioning is possibly too far forward

### ISSUE THREAD

**Issue by root-talis** [eezstreet/SWATEliteForce#502]
The model probably should be positioned further back along the arm, because now the officer's right hand floats in the air behind the grip.

![Image 004](https://user-images.githubusercontent.com/5227711/84050376-4c737b00-a9b6-11ea-850f-e6fa485e1336.png)
![Image 005](https://user-images.githubusercontent.com/5227711/84050383-50070200-a9b6-11ea-8bea-cda42f55978f.png)
![Image 008](https://user-images.githubusercontent.com/5227711/84050387-5301f280-a9b6-11ea-90ba-06fd43c2af68.png)

**Comment by eezstreet** [comment]
Fixed in v7.1.
