### ISSUE TITLE
Warnings in the SWAT4X.log 

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#517]
Warning: Missing Function Function Core.Object.ReplaceText

Warning: Class None.ini:Engine.Engine.DefaultPlayerMenu' could not be loaded: ini:Engine.Engine.DefaultPlayerMenu' not found in configuration file.

Warning: StaticMesh gear_sef.ProtectNVGUp' could not be loaded: Object 'StaticMesh gear_sef.ProtectNVGUp' not found.

Warning: Failed to load 'Texture gui_tex.resetbutton': Failed to find object 'Texture gui_tex.resetbutton'

Warning: Failed to load 'NULL': Can't resolve package name

Warning: Failed to load 'Class None.None': Can't resolve package name

**Comment by T-MaxWiese-T** [comment]
These warnings are also with other players, so you should study these warnings carefully.

**Comment by T-MaxWiese-T** [comment]
Warning: Failed to load 'Class DownloadMod.DLTimeOut': Can't find file for package 'DownloadMod'
GUI: GUIMultiComponent::AddComponent - Could not create component DownloadMod.DLTimeOut

**Comment by T-MaxWiese-T** [comment]
Also check if certain warnings are related to the General Protection Fault. This warning came just before the game crashed on my computer:
Warning: StaticMesh gear_sef.ProtectNVGUp' could not be loaded: Object 'StaticMesh gear_sef.ProtectNVGUp' not found.

**Comment by eezstreet** [comment]
> Warning: StaticMesh gear_sef.ProtectNVGUp' could not be loaded: Object 'StaticMesh gear_sef.ProtectNVGUp' not found.

This one is fixed via bc3c3ebb10e780a9e11999673ecc96161a0fcc55

> Warning: Class None.ini:Engine.Engine.DefaultPlayerMenu' could not be loaded: ini:Engine.Engine.DefaultPlayerMenu' not found in configuration file.
> Warning: Failed to load 'Texture gui_tex.resetbutton': Failed to find object 'Texture gui_tex.resetbutton'

These can be safely ignored as they refer to unused features (the warnings occur in the base game as well)

> Warning: Missing Function Function Core.Object.ReplaceText
> Warning: Failed to load 'Class DownloadMod.DLTimeOut': Can't find file for package 'DownloadMod'
> GUI: GUIMultiComponent::AddComponent - Could not create component DownloadMod.DLTimeOut

These are all caused by a mod conflict and aren't related to SEF.

> Warning: Failed to load 'NULL': Can't resolve package name
> Warning: Failed to load 'Class None.None': Can't resolve package name

I think this is caused by the No Weapon option in the loadout menu but I'm not 100% sure.

**Comment by T-MaxWiese-T** [comment]
Warning: ImportText failed in: (SpecificationType=SilencedMP5_1p_Fired,SpecificationClass=Class'IGSoundEffectsSubsystem.NormalSoundEffectSpe

Log: setActionParameters: WARNING: parameter BoolProperty SwatAICommon.AimAroundGoal.CancelWhenCompliant doesn't exist in action IdleAimAroundAction SP-Training.IdleAimAroundAction7
Log: setActionParameters: WARNING: parameter BoolProperty SwatAICommon.AimAroundGoal.CancelWhenCompliant doesn't exist in action IdleAimAroundAction SP-Training.IdleAimAroundAction8
Log: setActionParameters: WARNING: parameter BoolProperty SwatAICommon.AimAroundGoal.CancelWhenCompliant doesn't exist in action IdleAimAroundAction SP-Training.IdleAimAroundAction9
Log: setActionParameters: WARNING: parameter BoolProperty SwatAICommon.AimAroundGoal.CancelWhenCompliant doesn't exist in action IdleAimAroundAction SP-Training.IdleAimAroundAction10

**Comment by modotte** [comment]
Hello! A question. Where could I find this log file in my filesystem?
