### ISSUE TITLE
When you start SEF, the Vanilla logo is displayed and not the SEF logo

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#521]
![Screenshot (60)](https://user-images.githubusercontent.com/65263210/89110182-68d8e480-d448-11ea-8c47-f4b62229df75.png)
![color](https://user-images.githubusercontent.com/65263210/89110191-8017d200-d448-11ea-9b4e-70c1e8703218.png)

**Comment by eezstreet** [comment]
I prefer the existing one honestly. It’s customizable though, so if you want to make an add-on, feel free.
