### ISSUE TITLE
Bug: Black borders (valuable space)

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#524]
Solution: Make the edges smaller.
![8 02 20_0_-Shot00001_LI](https://user-images.githubusercontent.com/65263210/89117595-4a520800-d49f-11ea-9a7c-e9f52e0810c0.jpg)
![_-Shot00000](https://user-images.githubusercontent.com/65263210/89117596-4c1bcb80-d49f-11ea-97ab-a08d3045d6b1.png)

**Comment by eezstreet** [comment]
Not a bug.
