### ISSUE TITLE
When the FOV is set to maximum it comes to several unpleasant things.

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#525]
Too high FOV makes animations looks weird and makes weapons not big enough. In addition, the hands look quite long and from a distance the text is blurred. 
Solution: Since you can adjust both FOVs it does not seem to be a big problem. I would suggest that there should be a text that the player should adapt it.
![08_59_08 02 20_6_-Shot00000](https://user-images.githubusercontent.com/65263210/89117704-2f33c800-d4a0-11ea-97ea-808098141f60.png)
![09_02_08 02 20_4_-Shot00001](https://user-images.githubusercontent.com/65263210/89117705-30fd8b80-d4a0-11ea-81d7-6e0f02739cc6.png)
![09_02_08 02 20_7_-Shot00003](https://user-images.githubusercontent.com/65263210/89117775-b4b77800-d4a0-11ea-9c48-3363047c3def.png)

**Comment by eezstreet** [comment]
Not a bug...change the viewmodel FOV.
