### ISSUE TITLE
Lightstick keep falling from the floor

### ISSUE THREAD

**Issue by beppegoodoldrebel** [eezstreet/SWATEliteForce#530]
I've found a probable fix the bug , just need some more testing.

in the static mesh window:
- select the mesh 
- Collision Tools  and Fit 6-DOP(BOX)
- Collision Tools and Fit Cylinder Around Z

This result in this collision box:
![image](https://user-images.githubusercontent.com/69092966/89402706-8db6ab80-d717-11ea-9eb0-2a0e30695ff3.png)

**Comment by T-MaxWiese-T** [comment]
![144658](https://user-images.githubusercontent.com/65263210/89414356-8b118180-d72a-11ea-960d-43a75353f4f6.png)
:+1:

**Comment by eezstreet** [comment]
Does this result in any difference in how it behaves when rolling down inclines? See the Primary Entrance for Victory Imports. The hill is steep enough that light sticks should roll down it imo

**Comment by beppegoodoldrebel** [comment]
It slides more than rolling in that hill. 
I dont know, I guess we cant have all unfortunately.

**Comment by sandman332** [comment]
Even seeing like a side-by-side comparison video of the two would be interesting.  Honestly, I feel most players would rather them actually almost 100% not fall through the world and maybe slide/roll a bit differently then Light Sticks still falling through now and then with proper rolling/sliding.

**Comment by eezstreet** [comment]
This change has been implemented.
