### ISSUE TITLE
[BUG] Inital Dispatch Audio Not Playing By Default Except For Custom One's Like Meatbarn & Courthouse

### ISSUE THREAD

**Issue by sandman332** [eezstreet/SWATEliteForce#535]
Reposting from discord here.

I noticed that missions aren't playing their Inital Dispatch Audio's even if the checkbox in options isn't checked.  However the custom maps with custom dispatches like MeatBarn & CourtHouse continue to play theirs without issue.

**Comment by eezstreet** [comment]
Can’t reproduce. Are there specific missions or situations where it occurs?

**Comment by sandman332** [comment]
I tried loading up multiple missions via the campaign and the console, even joined online servers that were just starting a map but the Initial dispatches would never play except for the custom one's that were made for SEF Meatbarn & Courthouse.  The audio files still exist in my actual SWAT 4 folder as well (made sure they weren't blank files or deleted for whatever reason).  

This didn't seem to be an issue before v7.

**Comment by sandman332** [comment]
I have no idea what happened but something modified all the mission loading files and set them as "empty" files at 0 bytes.  I never installed any sort of "Disable Initial Dispatch" mod(s) either so I don't know what happened but replacing the files with the proper ones fixed it.
