### ISSUE TITLE
Players without a gas mask who are near a gas cloud get "Critical Error"

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#537]
With me the crash has already occurred in multiplayer and with Ryker and other players. The bug appears to occur randomly.
![5 041842](https://user-images.githubusercontent.com/65263210/90303508-c6404d00-deae-11ea-9458-a322d4db2140.png)
![5 04184245](https://user-images.githubusercontent.com/65263210/90303509-c93b3d80-deae-11ea-82f1-f25991e77d63.png)
![5 0418424576](https://user-images.githubusercontent.com/65263210/90303558-21723f80-deaf-11ea-890a-06a90ba6d59f.png)
![e3cdd6579e0eb6b496a9695032e5619d](https://user-images.githubusercontent.com/65263210/90464639-0e10df80-e10e-11ea-9714-5ebe2f8ee5b5.png)

**Comment by beppegoodoldrebel** [comment]
i've applied the commit but the problem is still there.
