### ISSUE TITLE
Suspects with pistols or shotguns can be easily tricked if you move and duck all the time

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#539]
The problem is that it is unrealistic and also in my opinion a bit of cheating. This is because the suspect AI first has to find a point and then has a certain reaction time to shoot.  If you stand in front of the suspect and move quickly and duck, the suspect will have difficulty shooting.

**Comment by eezstreet** [comment]
Fixed in a recent push.
