### ISSUE TITLE
Configurations Issue in 7.1

### ISSUE THREAD

**Issue by rubycookinson** [eezstreet/SWATEliteForce#550]
Left SWAT4 for a good month or so and just got back and downloaded this today, upgrading from an older version of v7.

I read the patch notes and it said you can now choose weapon configurations instead of the default M4A1, M4A1 Aim, etc.

I don't see any of these. Am I doing something wrong? Is it because I upgraded from an older version of v7?

![Screenshot_1](https://user-images.githubusercontent.com/57377930/91118924-e3131800-e646-11ea-8946-268d4b03b7ab.png)
![Screenshot_2](https://user-images.githubusercontent.com/57377930/91118927-e4dcdb80-e646-11ea-99cf-767f6734d21f.png)

**Comment by rubycookinson** [comment]
Alright, just did a clean install. This problem still remains. I think it might be a problem with the program rather than my install or version.

**Comment by rubycookinson** [comment]
Got it working, sorta. I’ll leave it open so you can see this and add a notice to do a fresh instal or something.

**Comment by T-MaxWiese-T** [comment]
Is this not the V7.1 Beta? If so, the configration function is not yet complete.
