### ISSUE TITLE
Error when loading a mission

### ISSUE THREAD

**Issue by rubycookinson** [eezstreet/SWATEliteForce#551]
Follow up to #550 

“Assertion Failed

Could not DLO invalid equipment class SwatEquipment.UMP45HoloSMG specified in the pocket specifications section of SwatEquipment.ini”

Love the mod. Love the idea of the update. Gonna play an older version til I can play this one. Keep up the good work!

**Comment by T-MaxWiese-T** [comment]
This does not seem to be a general problem.

**Comment by T-MaxWiese-T** [comment]
I also have the problem with the SEF GitHub version that doesn't load missions. I don't know exactly what the problem is. I always crash the game. You have to wait until eezstreet is back. But I do not have the error message with the UMP.

**Comment by Specia1** [comment]
@rubycookinson Did you ever fix it?
