### ISSUE TITLE
Optiwand bug 

### ISSUE THREAD

**Issue by Kenji-sp** [eezstreet/SWATEliteForce#567]
video: https://www.youtube.com/watch?v=t5dep_Stgr0
bug occurs when i request optiwand and give it back to the ai who gave it to me
the bug is that i still have an optiwand even after i gave it back and now the model of optiwand emerges with all other equipements.
video above for more explanation

**Comment by Masterscape** [comment]
![Thumbs Up](https://user-images.githubusercontent.com/70858087/116908792-fbaee580-ac4b-11eb-9965-1ee760121db3.png)

**Comment by eezstreet** [comment]
Fixed.
