### ISSUE TITLE
3440x1440 doesn't display as an option (v7)

### ISSUE THREAD

**Issue by wrapper** [eezstreet/SWATEliteForce#569]
I can see in the release notes that the following resolutions have been added:

Added 21:9 resolution options to the menus (2560x1080, 3440x1440, 3840x1600)

And I can see them in the GUI.ini file, however the choices I see in game are 2560x1440, 3840x2160 and 4096x2160

I don't see an option to toggle 21:9 which might be the issue?

**Comment by eezstreet** [comment]
It's there: https://i.imgur.com/7CXtcS3.png

**Comment by kevinfoley** [comment]
@eezstreet I still get this issue in SEF 7.1.
