### ISSUE TITLE
Crash probably due to SEFv7.1 source code changes

### ISSUE THREAD

**Issue by T-MaxWiese-T** [eezstreet/SWATEliteForce#582]
Critical: ASwatEnemy::execIsActorInSameZoneAsMe
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatEnemy.ActorIsInSameOrAdjacentZoneAsMe' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatEnemy.DropWeapon' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatEnemy.DropAllWeapons' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatEnemy.NotifyReadyToRagdoll' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatRagdollPawn.BecomeRagdoll' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatRagdollPawn.PlayDying' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='Engine.Pawn.Died' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatPawn.Died' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatRagdollPawn.Died' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatAI.Died' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatAICharacter.Died' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatEnemy.Died' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='Engine.Pawn.PostTakeDamage' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatPawn.PostTakeDamage' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='SwatGame.SwatAI.PostTakeDamage' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='Engine.Actor.TakeDamage' OBJ='SwatEnemy4']
Critical: UObject::CallFunction [SCRIPT='Engine.FiredWeapon.DealDamage' OBJ='SCARHAMG0']
Critical: UObject::CallFunction [SCRIPT='Engine.SwatWeapon.HandleProtectiveEquipmentBallisticImpact' OBJ='SCARHAMG0']
Critical: UObject::CallFunction [SCRIPT='Engine.SwatWeapon.HandleBallisticImpact' OBJ='SCARHAMG0']
Critical: UObject::CallFunction [SCRIPT='Engine.SwatWeapon.BallisticFire' OBJ='SCARHAMG0']
Critical: UObject::CallFunction [SCRIPT='Engine.FiredWeapon.TraceFire' OBJ='SCARHAMG0']
Critical: AActor::ProcessState [Stack: 'SCARHAMG SP-JewelryHeist.SCARHAMG0']
Critical: AActor::Tick [Actor: 'SCARHAMG0' Actor->bDeleteMe: FALSE]
Critical: AHandheldEquipment::Tick [(SCARHAMG SP-JewelryHeist.SCARHAMG0)]
Critical: TickAllActors
Critical: ULevel::Tick [(NetMode=0)]
Critical: TickLevel
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop->GenerateExtraCrashInfo [(GLevel: 'myLevel' PendingLevel: '(NULL)' NetMode: 'NM_Standalone']
Critical: MainLoop
Log: Exception handler: Flushing log file...
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: UALAudioSubsystem::ShutdownAfterError

**Comment by beppegoodoldrebel** [comment]
check enemyarchitypes.ini. 
There is probably some non-existent classes there. 

been there too.
