### ISSUE TITLE
Certain resolutions partially break Menu GUI

### ISSUE THREAD

**Issue by Silverfang22** [eezstreet/SWATEliteForce#6]
Resolutions available in video settings that cause certain pieces of menu to not have text appear:
1024x576
1152x648
1280x720
1280x768
1360x768
1366x768
1600x900
1680x1050

**Comment by eezstreet** [comment]
Maybe try using `setguires` option in the console to see if that helps? `setguires 1366x768` for example.

**Comment by eezstreet** [comment]
A recent commit improved upon this. Going to handle these on a case by case basis from now on.
