### ISSUE TITLE
Link to Microsoft Speech Recognition is broken

### ISSUE THREAD

**Issue by TheRisenPhoenix** [eezstreet/SWATEliteForce#608]
The link to Microsoft's Speech Recognition API doesn't work anymore. It looks like that Microsoft made the package unavailable for download. 
Is there any replacement link, perhaps to some cloud storage where the installer is still present?
Otherwise, it might be helpful to point this out in the readme, that there is currently no possibility to install the API.

**Comment by eezstreet** [comment]
So just FYI, if you use the Wayback machine, the download for it is still present and works (I tried it myself)
I will include a link to a public download, now that Microsoft no longer provides it.
