### ISSUE TITLE
Lowready position doesn't work when flashlight is turned on

### ISSUE THREAD

**Issue by modotte** [eezstreet/SWATEliteForce#636]
Hello :wave:.

I found that lowready position only works when you aim at civillians, your teammates or when you stand/crouch next to a wall/door/etc *and* when you have flashlight turned off, but when it is turned on, there's no lowready animation being initiated.

**Comment by beppegoodoldrebel** [comment]
not an issue , that's intentional

**Comment by modotte** [comment]
Ah alright. Ty for the info.
