### ISSUE TITLE
1911 iron sights offset

### ISSUE THREAD

**Issue by remyabel2** [eezstreet/SWATEliteForce#642]
Seems to be a regression in 7.1. Was fine in 7.0.

![Screenshot_2021-12-15_08-23-24](https://user-images.githubusercontent.com/94518122/146194286-99d73a1c-0348-4ee1-87e7-846af3547a01.png)

The front sight cannot be seen and the grouping is slightly to the right.

**Comment by remyabel2** [comment]
This commit seems to be the culprit: https://github.com/eezstreet/SWATEliteForce/commit/7558d1ce7bfe9f99a5cd6d90e68f2eb748578a9d. reverting these values fixes the issues. haven't tested the other weapons yet.

**Comment by raider1001** [comment]
Hmm, tested out that code commit with Glock 17, UMP, SCAR-H and M4 Super 90 and the they worked reasonably fine.
