### ISSUE TITLE
Food Wall HOM effect

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#66]
Breaking the front door of the Food Wall with a breaching shotgun leaves a pretty noticeable Hall of Mirrors effect - maybe it needs to kill the areaportal?

**Comment by theengineertcr** [comment]
This happens to any door that is breached, they leave a hall of mirrors effect where it shows the inside of a map/area. E.g metal doors have this metal window and after you breach it disappears, leaving you with a HOM.

**Comment by jose21crisis** [comment]
Something to be noted, suspects, hostages and SWAT can see through these Hall of Mirrors effect
