### ISSUE TITLE
Door sometimes cannot be interacted with using toolkit

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#75]
Had this happen with the first door to the right of sisters of mercy hostel.

**Comment by eezstreet** [comment]
It might be that the door is not considered lockable - lockable doors can't be used with the toolkit.

**Comment by theengineertcr** [comment]
Is there any reason why the door is not considered lockable? It seemed the same as any other door, having a knob and a keyhole.

**Comment by eezstreet** [comment]
The map itself would specify whether the door is locked. There's a few doors that cannot be locked at all, like the ones in St. Micheal's for instance. But those doors not being lockable is odd. My best guess is that the owners of the halfway house didn't want people to be able to lock themselves in rooms in case they are suicidal/won't take their medicine ;)

**Comment by eezstreet** [comment]
Closing this one for now. Doors that can't be locked will need to be reviewed on a case-by-case basis I think.
