### ISSUE TITLE
SWAT's do not open door after breaching with shotgun

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#77]
They don't deploy their grenades as well

**Comment by kevinfoley** [comment]
When you order AI officers to deploy breaching shotgun, they shoot about 10 inches to the left of the knob, missing it completely. They are never able to blast the lock.

**Comment by eezstreet** [comment]
This seems to be corrected (as does the bug that kevin mentioned), so I'm marking this as closed.
