### ISSUE TITLE
SWAT teams ignore next given commands in 2 situations

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#78]
When either blue or red team reports a suspect, the next given command will be ignored by the team. E.g, Blue team, open and clear(then they report a suspect) Red team starts to move towards room where blue team is, then I tell them to open and clear another room. Command is ignored and red team continues to move towards red team. When any team is within line of suspect who is complied, initiate command cannot be placed and any fall in command will be ignored while most other commands are not(like "MOVE TO").

**Comment by eezstreet** [comment]
This is intentional. They stop whatever they are doing if a suspect comes into their view.
