### ISSUE TITLE
Officers Can Not Shoot At Point Blank And Almost Point Blank Range Like Suspects Can

### ISSUE THREAD

**Issue by sandman332** [eezstreet/SWATEliteForce#80]
The officer ai can not shoot suspects at point blank range.  This always results in the suspect(s) killing my officer(s) because for whatever reason, the suspects can shoot officer fine point blank, but officers only aim their weapon at point blank, they don't shoot like suspects do.  Maybe they are trying to order compliance or something and it won't let them shoot?  No idea.

**Comment by eezstreet** [comment]
Does this still happen in the most recent v6?
