### ISSUE TITLE
Less Lethal Shotgun: Minimum Momentum?

### ISSUE THREAD

**Issue by eezstreet** [eezstreet/SWATEliteForce#89]
The LL Shotgun should maintain some form of minimum momentum so that it can trigger the stun effect, or the drag should be reduced slightly. As it stands, you can fire across the entry courtyard on Dupplessi's Diamonds and it won't trigger the stun effect because you are too far away.

**Comment by theengineertcr** [comment]
Recorded this but will not upload. Bug is obvious and I can confirm it. Depending on how far are you, I'd say around 9-10 meters away, you will not deal any damage or stun anyone while shooting at them using a beanbag shotgun. Tested on Tenement with Nova.

**Comment by sandman332** [comment]
I can also confirm this issue.  If it's really far then it won't do any stun damage.

**Comment by eezstreet** [comment]
I think we've decided that this is going to be the approach from here on. Closing.
