### ISSUE TITLE
Officers can fail a shotgun breach, a lot.

### ISSUE THREAD

**Issue by jose21crisis** [eezstreet/SWATEliteForce#93]
Simple Explaination. Simple solution. Force the door to be breached after the second shot.

**Comment by kevinfoley** [comment]
Should you just undo this commit? https://github.com/eezstreet/SWATEliteForce/pull/35/commits/92d1578f922eb49e3d1fa8b4ec01fb8fd963506d

**Comment by jose21crisis** [comment]
Probably.
