### ISSUE TITLE
Suspects being able to shoot while not facing directly at you and still deal damage

### ISSUE THREAD

**Issue by theengineertcr** [eezstreet/SWATEliteForce#98]
Most notable when a suspect is running and shooting while aiming at the sky or shooting while still turning around or attempting to interact with something.

**Comment by eezstreet** [comment]
Needs more information...is this happening in multiplayer? (might be due to lag) Singleplayer?

**Comment by theengineertcr** [comment]
This isn't a multiplayer bug, this is a SP bug. Need to check to make sure if this still happens.
